[
   ("docs/nootropics/2010-nehling.pdf", "/docs/nootropics/2010-nehlig.pdf")
   , (" lithium", "/Lithium")
   , ("docs/dnb/2005-fregni.pdf>. Acesso em: 19 mar. 2019.", "/docs/dnb/2005-fregni.pdf")
   , ("docs/iq/2018-plomin", "/docs/iq/2018-plomin.pdf")
   , ("Longevit", "/Longevity")
   , ("docs/catnip/2011-detry.pdf", "/docs/history/2011-detry.pdf")
   , ("docs/conscientiousness/2007-bishopclark.pdf apa citation", "/docs/conscientiousness/2007-bishopclark.pdf")
   , (" oolong", "/Tea#oolong")
   , ("Danbooru2018 原文網址：https://kknews.cc/comic/4kpg92q.html", "/Danbooru2018")
   , ("docs/melatonin /2014-boergers.pdf", "/docs/melatonin/2014-boergers.pdf")
   , ("docs/music-distraction/2005-Lesiuk.pdf", "/docs/music-distraction/2005-lesiuk.pdf")
   , ("docs/psychology/1952-asch", "/docs/psychology/1952-asch.pdf")
   , ("magnesium", "/nootropics/Magnesium")
   , ("Feed.hs", "https://github.com/jgm/gitit/blob/master/src/Network/Gitit/Feed.hs")
   , ("docs/sociology/2003-murray-humanaccomplishment.pdfwww.gwern.net", "/docs/sociology/2003-murray-humanaccomplishment.pdf")
   , ("Danbooru2018%20%E5%8E%9F%E6%96%87%E7%B6%B2%E5%9D%80%EF%BC%9Ahttps://kknews.cc/comic/4kpg92q.html", "/Danbooru2018")
   , ("Danbooru2018%E4%BD%9C%E8%80%85%EF%BC%9Agrapeothttps://www.bilibili.com/read/cv2175924%E5%87%BA%E5%A4%84%EF%BC%9A%20bilibili", "/Danbooru2018")
   , ("Danbooru2019", "/Danbooru2018")
   , ("dgoogle scholarocs/genetics/correlation/1998-oconnor-2.pdfgoogle", "/docs/genetics/correlation/1998-oconnor-2.pdf")
   , ("docs/fiction/anonymous-nessusdnd.pdf%20https://akinokure.blogspot.com/index.html", "/docs/fiction/2015-mellonbread-dnd-nessus.pdf")
   , ("docs/gentetics/correlation/1987-kendler.pdf", "/docs/genetics/correlation/1987-kendler.pdf")
   , ("docs/genetics/correlation/1995-kendler.pdfhttps://www.ncbi.nlm.nih.gov/pmc/articles/PMC4677147/index.html","/docs/genetics/correlation/1995-kendler.pdf")
   , ("docs/iq/2014-carl.pdf&ved=2ahUKEwjqqa7Go7LhAhWMpIsKHeVrDW0QFjAAegQIAhAB&usg=AOvVaw1hTwJLlXBed-SoxCfn0zGa?fbclid=IwAR3FZlpEUvki5VKCahdcayUcOGSZzKupTj_pmmv0i-RxbrEVbnB9cKilQU8", "/docs/iq/2014-carl.pdf")
   , ("docs/iq/2015-st...", "/docs/iq/2015-strenze.pdf")
   , ("docs/iq/2019-alemany.pd", "/docs/iq/2019-alemany.pdf")
   , ("docs/sunkcosts/1984-bozerman.pdf", "/docs/sunkcosts/1984-bazerman.pdf")
   , ("docs/sunkcosts/1995-hoang", "/docs/sunkcosts/1995-hoang.pdf")
   , ("nootropics/Zeo", "/Zeo")
   , ("spaced-repetion", "/Spaced-repetition")
   , ("tags/bitcoin", "/tags/Bitcoin")
   , ("tags/dnb", "/tags/DNB")
   , ("tags/silk road", "/tags/Silk Road")
   , ("statistics/decision/1954-tukey.pdf", "/docs/statistics/decision/1954-tukey.pdf")
   , ("everything", "/Everything")
   , ("docs/dnb/2000- butzlaff.pdf", "/docs/dnb/2000-butzlaff.pdf")
   , ("docs/algernon/1995-rechtschaffen", "/docs/algernon/1995-rechtschaffen.pdf")
   , ("docs/genetics/correlations/2017-akiyama.pdf", "/docs/genetics/correlation/2017-akiyama.pdf")
   , ("docs/spacedrepetition/2012-muflax-dreamingofaworldundone.html", "/docs/spacedrepetition/2012-muflax-dreamingofaworldundone.html.maff")
   , ("Facesv", "/Faces")
   , ("docs/melatonin/2014-boergers.pdf. Times.pdf", "/docs/melatonin/2014-boergers.pdf")
   , ("TWDNEthiswaifudoesnotexist.net", "/TWDNE")
   , ("thiswaifudoesntexist/index.html", "https://www.thiswaifudoesnotexist.net/")
   , ("Coin-Flip", "/Coin-flip")
   , ("docs/anime/danbooru2017", "/Danbooru2018")
   , ("docs/melatonin/2014-boergers.pdf.Times.pdf", "/docs/melatonin/2014-boergers.pdf")
   , ("docs/melatoin/2014-boergers.pdf", "/docs/melatonin/2014-boergers.pdf")
   , ("docs/nature/2010-peen.pdf.", "/docs/nature/2010-peen.pdf")
   , ("Embryo selection.", "/Embryo-selection")
   , ("google-shutdowns", "/Google-shutdowns")
   , ("Melatonincd", "/Melatonin")
   , ("modafnil", "/Modafinil")
   , ("docs/japanese/1940-nippongakujutsushinkokan-manyoshu.pdf", "/docs/japanese/1940-nippongakujutsushinkokai-manyoshu.pdf")
   , ("docs/music-distraction/2014-perham.pdf .", "/docs/music-distraction/2014-perham.pdf")
   , ("docs/spacedrepetition/1986-goode.pdf%EF%BB%BF", "/docs/spacedrepetition/1986-goode.pdf")
   , ("statics/css/default.css", "/static/css/default.css")
   , ("Blackmarket survival", "/DNM-survival")
   , ("caffeine", "/zeo/Caffeine")
   , ("complment", "/Complement")
   , ("Danbooru2015", "/Danbooru2018")
   , ("docs/economics/1968-thomas.pdf)", "/docs/economics/1968-thomas.pdf")
   , ("docs/genetics/editing/2017-scheufele.pdf.", "/docs/genetics/editing/2017-scheufele.pdf")
   , ("docs/longevity/2019-vrselja.pdf&ved=2ahUKEwjoz72F69fhAhWRDewKHevaCWMQFjAAegQIAxAB&usg=AOvVaw2p7iJrPDjEvKUUXtEmqSCG&cshid=1555528546459", "/docs/longevity/2019-vrselja.pdf")
   , ("docs/nature/2010-peen.pdf - The current status of urban-rural differencesin psychiatric disorders", "/docs/nature/2010-peen.pdf")
   , ("docs/spacedrepetition/2007-rohrer.pdf%EF%BB%BF", "/docs/spacedrepetition/2007-rohrer.pdf")
   , ("docspsychology/1952-asch.pdf", "/docs/psychology/1952-asch.pdf")
   , ("lsdmicrodosing", "/LSD-microdosing")
   , ("newsletter/2014/0l01", "/newsletter/2014/01")
   , ("newsletter/2014/0ll1", "/newsletter/2014/01")
   , ("Superrationa", "/docs/xrisks/1985-hofstadter")
   , ("r/DarkNetMarkets/comments/30tudk/psa_5_reddit_accounts_subpoenaed_by_ice/index.html?utm_name=DarkNetMarkets", "/docs/sr/2015-03-30-gwern-redditsubpoena.html")
   , ("Aboutpage", "/About.page")
   , ("docs/iq/1966-shuey-thetestingofnegrointelligencevol1.pdf)", "/docs/iq/1966-shuey-thetestingofnegrointelligencevol1.pdf")
   , ("donate", "https://www.patreon.com/gwern")
   , ("Danbooru2018原文網址：https://kknews.cc/zh-tw/comic/3a3ap4a.html", "/Danbooru2018")
   , ("dics/dnb/2000-vaughn.pdf", "/docs/dnb/2000-vaughn.pdf")
   , ("docs/ai/2019-anumanchipalli.pdf---", "/docs/ai/2019-anumanchipalli.pdf")
   , ("docs/ai/2019-anumanchipalli.pdf.", "/docs/ai/2019-anumanchipalli.pdf")
   , ("docs/borges/1936-borgesthetranslatorsofthethousandandonenights.pdf", "docs/borges/1936-borges-thetranslatorsofthethousandandonenights.pdf")
   , ("docs/conscientiousness/1994-krueger.", "/docs/conscientiousness/1994-krueger.pdf")
   , ("docs/eva/null", "/docs/eva/index.html")
   , ("docs/iq/2018-rindermann.pdf (https://www.gwern.net/docs/iq/2018-rindermann.pdf", "/docs/iq/2018-rindermann.pdf")
   , ("docs/iq/2018-rindermann.pdf (https://www.gwern.net/docs/iq/2018-rindermann.pdf)", "/docs/iq/2018-rindermann.pdf")
   , ("docs/japanese/1997-tsuzuki-tokyoacerta?fbclid=IwAR3VGSgGB_oFbkju-ydkbfUJ_5sNI49QqRxe_zZB162YE-ytkRsi-hYS2wc", "/docs/japanese/1997-tsuzuki-tokyoacertainstyle.pdf")
   , ("docs/modafinil/1988-bastuji.pdf.", "/docs/modafinil/1988-bastuji.pdf")
   , ("docs/music-dpurnell webb and speelmanistraction/1989-salame.pdf", "/docs/music-distraction/1989-salame.pdf")
   , ("docs/psychology/1952-asch.pd", "/docs/psychology/1952-asch.pdf")
   , ("FAces", "/Faces")
   , ("Self-decrypting-file", "/Self-decrypting-files")
   , ("eveything", "/Everything")
   , ("Eveything", "/Everything")
   , ("ieverything", "/Everything")

   , ("docs/algernon/2006-harris.pdf)", "/docs/algernon/2006-harris.pdf")
   , ("docs/spaced repetition/1987-bahrick.pdf", "/docs/spacedrepetition/1987-bahrick.pdf")
   , ("docs/spacedrepetition/1987- bahrick.pdf", "/docs/spacedrepetition/1987-bahrick.pdf")
   , ("docs/spacedrepetition/1987-%20bahrick.pdf", "/docs/spacedrepetition/1987-bahrick.pdf")
   , ("Tasks", "/Tanks")
   , ("Danbooru2018 原文網址：https://mttmp.com/cijjxnk.html", "/Danbooru2018")
   , ("dnm-archive", "/DNM-archives")
   , ("docs/20081003-nakamoto-bitcoindraft.pd", "/docs/bitcoin/20081003-nakamoto-bitcoindraft.pdf")
   , ("docs/ai/2019-anumanchipalli.pdf 原文網址：https://kknews.cc/science/66zoyvl.html", "/docs/ai/2019-anumanchipalli.pdf")
   , ("docs/genetics/selction/1977-todd.pdf", "/docs/genetics/selection/1977-todd.pdf")
   , ("docs/iq/2009-richwine.pdf&ved=2ahUKEwj0tf768fPhAhXaFjQIHUY6DHAQFjAEegQIBBAB&usg=AOvVaw27jr39IWA2u_bQbOXYJukN?fbclid=IwAR2d_TuC8KCmP1K4rAqzN7q2ST47TEBffYzz5m_hIaCyLqoatCkO4NXOMuo", "/docs/iq/2009-richwine.pdf")
   , ("docs/melatonin/2009-burkhart.pdf.", "/docs/melatonin/2009-burkhart.pdf")
   , ("docs/music-distraction/2005-lesiuk.pdf&ved=2ahUKEwiXjYD2p4LiAhW8HjQIHUKUBcoQFjAAegQIAxAB&usg=AOvVaw0Gg776a4B-kua4OH8kBpEW", "/docs/music-distraction/2005-lesiuk.pdf")
   , ("docs/music-distraction/2011-huang.pdfhttps://scholar.google.com.mx/scholar?hl=es&as_sdt=0,5&q=classical+music+decibels+concentration&btnG=", "/docs/music-distraction/2011-huang.pdf")
   , ("docs/rl/2016-graves.pd", "/docs/rl/2016-graves.pdf")
   , ("images/mooreslaw-marketvolumelaw", "/images/mooreslaw-marketvolumelaw.png")
   , ("Silk-Road.txt", "/Silk-Road.page")
   , ("static/font/SourceSansPro-BASIC-BlackItalic.ttf'", "/static/font/SourceSansPro-BASIC-BlackItalic.ttf")
   , ("writings/changes", "/Changelog")
   , ("docs/ai/2019/anumanchipalli.pdf", "/docs/ai/2019-anumanchipalli.pdf")
   , ("index l theanine + caffeine", "/index")
   , ("docs/music-distraction/1989-salame", "/docs/music-distraction/1989-salame.pdf")
   , ("Docs/Music-Distraction/2002-Hallam.pdf", "/docs/music-distraction/2002-hallam.pdf")
   , ("Drug-heuristic", "/Drug-heuristics")
   , ("docs/sr/docs/sr/2015-03-18-the_avid-evolutionmarketbackground-cardingforumsponzischemesle.html", "/docs/sr/2015-03-18-the_avid-evolutionmarketbackground-cardingforumsponzischemesle.html")
   , ("docs/sr/docs/sr/2014-01-02-deepdotweb-flomarketexitscam.html", "/docs/sr/2014-01-02-deepdotweb-flomarketexitscam.html")
   , ("docs/sr/docs/sr/2014-01-09-deepdotweb-flomarketinterview.html", "/docs/sr/2014-01-09-deepdotweb-flomarketinterview.html")
   , ("docs/sr/docs/sr/2014-01-23-deepdotweb-outlawmarketinterview.html", "/docs/sr/2014-01-23-deepdotweb-outlawmarketinterview.html")
   , ("docs/sr/docs/sr/2014-01-27-deepdotweb-pandoramoderatorhack.html", "/docs/sr/2014-01-27-deepdotweb-pandoramoderatorhack.html")
   , ("docs/sr/docs/sr/2014-02-12-deepdotweb-theutopiabust.html", "/docs/sr/2014-02-12-deepdotweb-theutopiabust.html")
   , ("docs/sr/docs/sr/2014-02-21-deepdotweb-darknetnationinterview.html", "/docs/sr/2014-02-21-deepdotweb-darknetnationinterview.html")
   , ("docs/sr/docs/sr/2014-03-12-deepdotweb-hansamarketdoxxed.html", "/docs/sr/2014-03-12-deepdotweb-hansamarketdoxxed.html")
   , ("docs/sr/docs/sr/2014-03-18-deepdotweb-evolutionexitscam130kbtclost.html", "/docs/sr/2014-03-18-deepdotweb-evolutionexitscam130kbtclost.html")
   , ("docs/sr/docs/sr/2014-03-20-deepdotweb-pandorahacked.html", "/docs/sr/2014-03-20-deepdotweb-pandorahacked.html")
   , ("docs/sr/docs/sr/2014-04-08-deepdotweb-therealdeal.html", "/docs/sr/2014-04-08-deepdotweb-therealdeal.html")
   , ("docs/sr/docs/sr/2014-04-19-deepdotweb-1776announcement.html", "/docs/sr/2014-04-19-deepdotweb-1776announcement.html")
   , ("docs/sr/docs/sr/2014-08-01-deepdotweb-outlawmarketclosed.html", "/docs/sr/2014-08-01-deepdotweb-outlawmarketclosed.html")
   , ("docs/sr/docs/sr/2014-09-23-deepdotweb-newdetailsabouttheutopiamarketplacebust.html", "/docs/sr/2014-09-23-deepdotweb-newdetailsabouttheutopiamarketplacebust.html")
   , ("docs/sr/docs/sr/2014-11-09-deepdotweb-pedofunding.html", "/docs/sr/2014-11-09-deepdotweb-pedofunding.html")
   , ("docs/sr/docs/sr/2014-11-11-deepdotweb-hydraadminarrest.html", "/docs/sr/2014-11-11-deepdotweb-hydraadminarrest.html")
   , ("docs/sr/docs/sr/2015-01-14-deepdotweb-israeliteenarrested.html", "/docs/sr/2015-01-14-deepdotweb-israeliteenarrested.html")
   , ("docs/sr/docs/sr/2015-05-12-deepdotweb-translationhuntunderway.html", "/docs/sr/2015-05-12-deepdotweb-translationhuntunderway.html")
   , ("docs/sr/docs/sr/2015-06-02-deepdotweb-poseidonmarketdoxxed.html", "/docs/sr/2015-06-02-deepdotweb-poseidonmarketdoxxed.html")
   , ("docs/sr/docs/sr/2015-06-04-deepdotweb-utopiamarketadmincosanostra.html", "/docs/sr/2015-06-04-deepdotweb-utopiamarketadmincosanostra.html")
   , ("docs/sr/docs/sr/2015-07-07-deepdotweb-agorabansguns.html", "/docs/sr/2015-07-07-deepdotweb-agorabansguns.html")
   , ("docs/sr/docs/sr/2015-07-16-deepdotweb-pedofundingdashcoin.html", "/docs/sr/2015-07-16-deepdotweb-pedofundingdashcoin.html")
   , ("docs/sr/docs/sr/2015-08-09-deepdotweb-eastindiacompanyhack.html", "/docs/sr/2015-08-09-deepdotweb-eastindiacompanyhack.html")
   , ("docs/sr/docs/sr/2015-08-10-deepdotweb-thestoryofanunluckyitaliancyberpusher.html", "/docs/sr/2015-08-10-deepdotweb-thestoryofanunluckyitaliancyberpusher.html")
   , ("docs/sr/docs/sr/2015-09-05-deepdotweb-darknetvendorsentencedto8years.html", "/docs/sr/2015-09-05-deepdotweb-darknetvendorsentencedto8years.html")
   , ("docs/sr/docs/sr/2015-11-29-deepdotweb-theidealisticmotivesbehindvalhalla.html", "/docs/sr/2015-11-29-deepdotweb-theidealisticmotivesbehindvalhalla.html")
   , ("docs/sr/docs/sr/2016-02-09-deepdotweb-horticulturalstudentinperth.html", "/docs/sr/2016-02-09-deepdotweb-horticulturalstudentinperth.html")
   , ("docs/sr/docs/sr/2016-08-12-deepdotweb-fedsindicttwoalphabayvendors.html", "/docs/sr/2016-08-12-deepdotweb-fedsindicttwoalphabayvendors.html")
   , ("docs/sr/docs/sr/2016-09-21-deepdotweb-alaskanmanarrested.html", "/docs/sr/2016-09-21-deepdotweb-alaskanmanarrested.html")
   , ("docs/sr/docs/sr/2016-11-04-deepdotweb-belgianvendorarrestedinsufficientpostage.html", "/docs/sr/2016-11-04-deepdotweb-belgianvendorarrestedinsufficientpostage.html")
   , ("docs/sr/docs/sr/2017-04-07-deepdotweb-afterhoursentenced.html", "/docs/sr/2017-04-07-deepdotweb-afterhoursentenced.html")
   , ("docs/sr/docs/sr/2019-01-24-deepdotweb-dnmlistchangelog.html", "/docs/sr/2019-01-24-deepdotweb-dnmlistchangelog.html")
   , ("docs/sr/docs/sr/2019-04-22-deepdotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/2019-06-??-deepdotweb-dnmlist.html=", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("Drug-heurist", "/Drug-heuristics")
   , ("Facesより)", "/Faces")
   , ("market/item/stilnoct-swedish-pharmacy-10mg-01d3b46686", "/tags/Silk%20Road")
   , ("docs/anime/2013-arudou.pdf.", "/docs/anime/2013-arudou.pdf")
   , ("docs/iq/1996-gendreau.Gendreau & Swartz (2009) demonstrated there are more effective outcomes if intervention programmes include the elements of risk, need and responsivity, in comparison to alternative", "/docs/iq/1996-gendreau.pdf")
   , ("docs/iq/1996-gendreau.", "/docs/iq/1996-gendreau.pdf")
   , ("does/statictics/1973-meshalkin-collectionofproblemsinprobabilitytheony.pdf", "/docs/statistics/1973-meshalkin-collectionofproblemsinprobabilitytheory.pdf")
   , ("Mail-deliveryusps", "/Mail-delivery")
   , ("docs/sociology/1997-rossi", "/docs/sociology/1987-rossi")
   , ("docs/ai/2019-05-13-gpt2-poetry-335m-5000samples.txt", "/docs/ai/2019-05-13-gpt2-poetry-345m-5000samples.txt")
   , ("modus", "/Modus")
   , ("modus-ponens", "/Modus")
   , ("modus-tollens", "/Modus")
   , ("Modus-ponens", "/Modus")
   , ("Modus-tollens", "/Modus")
   , ("ai/2019-05-13-gpt2-poetry-345m-5000samples.txt", "/docs/ai/2019-05-13-gpt2-poetry-345m-5000samples.txt")
   , ("docs/psychology/ 1952-asch.pdf", "/docs/psychology/1952-asch.pdf")
   , ("docs/radiance/198 @BOOK {chesney, |4-berger.pdf", "/docs/radiance/1984-berger.pdf")
   , ("docs/statistics/2015-franco.pdf http:/van Erp, S., Verhagen, J., Grasman, R., & Wagenmakers,E. (2013). Estimates of Between-Study Heterogeneityfor 705 Meta-Analyses Reported in PsychologicalBulletin From 1990-2013.journals.sagepub.com/doi/10.1177/1948550615598377", "/docs/statistics/2015-franco.pdf")
   , ("...longevity/2014-bannister.pdf", "/docs/longevity/2014-bannister.pdf")
   , ("DNM archives.", "/DNM-archives")
   , ("docs/economics/1927-ramsey.pd", "/docs/economics/1927-ramsey.pdf")
   , ("docs/genetics/editing/2019-south.", "/docs/genetics/editing/2019-south.pdf")
   , ("docs/iq/2016-boccio.pdf<", "/docs/iq/2016-boccio.pdf")
   , ("docs/nature/2010-peen.pd", "/docs/nature/2010-peen.pdf")
   , ("docs/psychology/1977-ross.pdf.", "/docs/psychology/1977-ross.pdf")
   , ("usesthis", "/Links#uses-this")
   , ("research", "/Research-criticism")
   , ("Research", "/Research-criticism")
   , ("Research-critic", "/Research-criticism")
   , ("Research-critique", "/Research-criticism")
   , ("reseach", "/Research-criticism")
   , ("research-criticism", "/Research-criticism")
   , ("docs/genetics/heritable/1967-goslin-teachersandtesting.pdf (teachers and ability 1967)", "/docs/genetics/heritable/1967-goslin-teachersandtesting.pdf")
   , (" docs/genetics/heritable/1967-goslin-teachersandtesting.pdf", "/docs/genetics/heritable/1967-goslin-teachersandtesting.pdf")
   , ("docs/music-distraction/2011-huang.pd", "/docs/music-distraction/2011-huang.pdf")
   , ("GPT", "/GPT-2")
   , ("GPT-", "/GPT-2")
   , ("GPT2", "/GPT-2")
   , ("Gpt-2", "/GPT-2")
   , ("Gpt2", "/GPT-2")
   , ("gpt", "/GPT-2")
   , ("gpt-", "/GPT-2")
   , ("gpt-2", "/GPT-2")
   , ("gpt2", "/GPT-2")
   , ("GPT-1", "/GPT-2")
   , ("mofafinil", "/Modafinil")
   , ("terrorism-is-not-effective", "/Terrorism-is-not-Effective")
   , ("terrorism", "/Terrorism-is-not-about-Terror")
   , ("spaced reoetition", "/Spaced-repetition")
   , ("Blackmailfail", "/Blackmail")
   , ("docs/bitcoin/20081003-nakamoto", "/docs/bitcoin/20081003-nakamoto-bitcoindraft.pdf")
   , ("docs/borges/1936-borges-ahistoryofeternity.pd", "/docs/borges/1936-borges-ahistoryofeternity.pdf")
   , ("docs/dnb/2003-jaeggi.pdf)", "/docs/dnb/2003-jaeggi.pdf")
   , ("docs/genetics/heritable/2019-barlow.pd", "/docs/genetics/heritable/2019-barlow.pdf")
   , ("docs/predictions/2001-armstrong-principlesforecasting", "/docs/predictions/2001-armstrong-principlesforecasting.pdf")
   , ("About exit scam", "/About")
   , ("docs/dnb/2003-jaeggi.pdf /index.html", "/docs/dnb/2003-jaeggi.pdf")
   , ("docs/genetics/heritable/2019-barlow.pdf:", "/docs/genetics/heritable/2019-barlow.pdf")
   , ("Clones", "/Clone")
   , ("Dog-clone", "/Clone")
   , ("dog-clone", "/Clone")
   , ("Dog-cloning", "/Clone")
   , ("dog-cloning", "/Clone")
   , ("docs/dnb/2000-vaughan.pdf. Accessed 30 May 2019", "/docs/dnb/2000-vaughan.pdf")
   , ("docs/dnb/2005-ackerman.pdf.", "/docs/dnb/2005-ackerman.pdf")
   , ("docs/eva/2010-crchttps://www.gwern.net/docs/eva/2010-crc", "/docs/eva/2010-crc")
   , ("website", "/index")
   , ("docs/borges/1947-borges-anewrefutationoftime.pdf.", "/docs/borges/1947-borges-anewrefutationoftime.pdf")
   , ("docs/borges/1977-borges-blindness.pdf.", "/docs/borges/1977-borges-blindness.pdf")
   , ("docs/genetics/correlation/2019-baselmans", "/docs/genetics/correlation/2019-baselmans.pdf")
   , ("Everything - everything is correlated", "/Everything")
   , ("Statistic=", "/Statistical-notes")
   , ("i", "/iq")
   , ("dfoods to.redce dihetaocs/economics/2011-ziobrowski.pdf", "/docs/economics/2011-ziobrowski.pdf")
   , ("About)", "/About")
   , ("doc/statistics/decision/1939-pearson.pdf", "/docs/statistics/decision/1939-pearson.pdf")
   , ("docs/bitcoin/1963-brown-pacioloonaccou...", "/docs/bitcoin/1963-brown-pacioloonaccounting.pdf")
   , ("index open", "/index")
   , ("Linkshttps://www.gwern.net/Mistakes", "/Links")
   , ("newsleter", "/tags/newsletter")
   , ("RNNmetadata", "/RNN-metadata")
   , ("Stress", "/On-Stress")
   , ("socks", "/Socks")
   , ("sock", "/Socks")
   , ("Sock", "/Socks")
   , ("statistics/bias/1975-rosenthal-experimenterexpectancyeffects.pdf", "/docs/statistics/bias/1975-rosenthal-experimenterexpectancyeffects.pdf")
   , ("docs/longevity/2017-kirkland", "/docs/longevity/2017-kirkland.pdf")
   , ("docs/psychology/1941-cleckley-maskofsanity.pdfCleckley, H. (1976). The mask of sanity: An attempt to clarify some issues about the so-called psychopathic personality (5th ed.). St. Louis, MO: Mosby", "/docs/psychology/1941-cleckley-maskofsanity.pdf")
   , ("docs/sociology/2003-murray-humanaccomplishment.pdf&ved=2ahUKEwj-rLfEv9_iAhWDjYsKHd3AA-MQFjALegQIARAB&usg=AOvVaw3AB3oisqc2OBZbyj2hKWJL&cshid=1560189726029?fbclid=IwAR2eQCXqidkRPhBRZTOc8ewvrBIWS0vao9TxwGPqbQL4EkKaKk_FlXiSa6w", "/docs/sociology/2003-murray-humanaccomplishment.pdf")
   , ("Nootropicsmixing up graphic symbols", "/Nootropics")
   , ("research-bounties", "/Fulltext")
   , ("Research-bounties", "/Fulltext")
   , ("Research-Bounties", "/Fulltext")
   , ("research-Bounties", "/Fulltext")
   , ("docs/statistics/meta-analysis/2004-hunterschmidt-methodsofmetaanalysis.pdf<br><br><br>Much", "/docs/statistics/meta-analysis/2004-hunterschmidt-methodsofmetaanalysis.pdf")
   , ("docs/borges/1951-borges-pascal.pdf", "/docs/borges/1951-borges-pascalssphere.pdf")
   , (".../psychology/.../1980-hartley-thepsychologyofwrittencommunication", "/docs/psychology/writing/1980-hartley-thepsychologyofwrittencommunication.pdf")
   , (" author", "/Links")
   , ("docs/cs/1982-perlis.pdf'", "/docs/cs/1982-perlis.pdf")
   , ("docs/iq/1963-rosenthal.pdf&ved=2ahUKEwjx-dmt5eviAhUBmlkKHWYkBFcQFjAHegQIARAB&usg=AOvVaw10-03O1gOPuyuQ7JajfGzY", "/docs/iq/1963-rosenthal.pdf")
   , ("docs/statistics/decisions", "/docs/statistics/decision/index.html")
   , ("FTanks", "/Tanks")
   , ("timing", "/Timing")
   , ("Media-Lab", "/Timing")
   , ("Media-lab", "/Timing")
   , ("media-lab", "/Timing")
   , ("Tining", "/Timing")
   , ("Timning", "/Timing")
   , ("bookshelf", "/Books")
   , ("docs/culture/2010-dobelli.pdf&ved=2ahUKEwjegNGJ_PXiAhXBk4sKHe7zC_YQFjAAegQIARAB&usg=AOvVaw2tAxL_d3sJEtug1zIGDq87&cshid=1560962048169", "/docs/culture/2010-dobelli.pdf")
   , ("About.site", "/About#site")
   , ("docs/iq/2007-strenze.pdf&ved=2ahUKEwjVlbnIx_PiAhWs-ioKHUYzD3oQFjAAegQIAhAB&usg=AOvVaw1qc8H3nnM1YwkEeYDoklG1", "/docs/iq/2007-strenze.pdf")
   , ("modafin", "/Modafinil")
   , ("docs/statistics/peerreview/2017-goldestein.pdf", "/docs/statistics/peerreview/2017-goldstein.pdf")
   , ("docs/genetics/correlation/2019-wojcik.pdfpre-check your script", "/docs/genetics/correlation/2019-wojcik.pdf")
   , ("docs/genetics/heritable/1984-buss-temperamentearlydevelopingpersonalitytraits.pdf)", "/docs/genetics/heritable/1984-buss-temperamentearlydevelopingpersonalitytraits.pdf)")
   , ("docs/iq/2014-carl.pd", "/docs/iq/2014-carl.pdf")
   , ("docs/longevity/2014-bannister.pdf.", "/docs/longevity/2014-bannister.pdf")
   , ("account/profile/05abde47fcf35cd033ff12b9254bf3a0/4", "/index")
   , ("dos/math/2009-sinclair.pd", "/docs/math/2009-sinclair.pdf")
   , ("Facesより", "/Faces")
   , ("docs/iq/1938-cattell.pdf)", "/docs/iq/1938-cattell.pdf")
   , ("docs/math/2009-sinclair-pdf", "/docs/math/2009-sinclair.pdf")
   , ("acd123459879.lkj?vf=vfd", "/index")
   , ("docs/iq/2014-hyde.pdf.", "/docs/iq/2014-hyde.pdf")
   , ("dozi8hz/jfiops.sxc", "/index")
   , ("dtyu<script>2644.igr?vf=jky", "/index")
   , ("jkstatus", "/index")
   , ("sgty76hu3f09", "/index")
   , ("docs/psychology/1996-rachman.pdf",  "/docs/psychology/1966-rachman.pdf")
   , ("dnm survival", "/DNM-survival")
   , ("docs/genetics/heritable/2018-khera.pdf**==?tdsourcetag=s_pctim_aiomsg", "/docs/genetics/heritable/2018-khera.pdf")
   , ("docs/music-distraction/2005-lesiu", "/docs/music-distraction/2005-lesiuk.pdf")
   , ("docs/sr/2019-04-22-deepweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/2019-04-22deepweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/2019-04022deepweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/null", "/docs/sr/index.html")
   , ("docs/catnip/3000-turner-thedomesticcat.pdf", "/docs/catnip/2000-turner-thedomesticcat.pdf")
   , ("docs/iq/2013-lynn.pdf (old data)", "/docs/iq/2013-lynn.pdf")
   , ("docs/spacedrepetition/1939-spitzer", "/docs/spacedrepetition/1939-spitzer.pdf")
   , ("Spaced-repetition for", "/Spaced-repetition")
   , ("blackmarket archives", "/DNM-archives")
   , ("docs/anime/2014-tamer...", "/docs/anime/2014-tamerlane-animeyearbyyear-2001.html")
   , ("Charity", "/Charity-is-not-about-helping")
   , ("docs/genetics/heritable/1966-heston", "/docs/genetics/heritable/1966-heston.pdf")
   , ("docs/genetics/selection/2000-kaback.pdf)", "/docs/genetics/selection/2000-kaback.pdf")
   , ("docs/japanese/2001-debary-sourcesofjapanesetradition", "/docs/japanese/2001-debary-sourcesofjapanesetradition.pdf")
   , ("docs/statistics/decision/1986-stephens-foragingtheory.pdfAnts at work: How an insect society is organized.", "/docs/statistics/decision/1986-stephens-foragingtheory.pdf")
   , ("images/rl/2018-metz-table1-metalearni=", "/images/rl/2018-metz-table1-metalearningparadigms.png")
   , ("dambooru2018", "/Danbooru2018")
   , ("Magnesium", "/nootropics/Magnesium")
   , ("docs/iq/2019-jiang.pdf?origin_team=T542U849X", "/docs/iq/2019-jiang.pdf")
   , ("docs/sr/2019-04-22-deepdotweb-dnmlist.htmlxme", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , (" spaced repetition", "/Spaced-repetition")
   , ("account/profile/05abde47fcf35cd033ff12b9254bf3a0/2", "/tags/Silk%20Road")
   , ("black-market", "/tags/Silk%20Road")
   , ("Danbooru2018原文網址：https://kknews.cc/comic/3a3ap4a.html", "/Danbooru2018")
   , ("Danbooru2018 原文網址：https://kknews.cc/comic/3a3ap4a.html", "/Danbooru2018")
   , ("docs/psychology/2006-feist.pdfhttps://mail.ru", "/docs/psychology/2006-feist.pdf")
   , ("docs/psychology/okcupid/yourlooksandyourinbox", "/docs/psychology/okcupid/yourlooksandyourinbox.html")
   , ("docs/spacedrepetition/2012-mcdaniel.pdf\"Using quizzes to enhance summative-assessment performance in a web-based class: An experimental study\"", "/docs/spacedrepetition/2012-mcdaniel.pdf")
   , ("docs/sr/caligirl-profile.ht", "/wiki/docs/sr/caligirl-profile.htm")
   , ("market/item/amfetamin-100gram-klet-dunder-17d57ed2a8", "/tags/Silk%20Road")
   , ("market/item/weed-hawaiian-snow-4-gram-f408fb748c", "/tags/Silk%20Road")
   , ("newsletter/2019/june", "/newsletter/2019/06")
   , ("zeo/Magnesium", "/zeo/ZMA")
   , ("docs/iq/smpy/1986-renzulli systemsandmodelsforprogramsforgiftedtalented.pdf", "/docs/iq/smpy/1986-renzulli-systemsandmodelsforprogramsforgiftedtalented.pdf")
   , ("Faces quilt", "/Faces#applications")
   , ("style.css", "/static/css/default.css")
   , ("docs/biology/2019-vallescolomer.pdf&hl=pt-BR&sa=X&scisig=AAGBfm2-09J4Xc9FHgHQ-x3-Pv8E6Gb_1g&nossl=1&oi=scholarr?fbclid=IwAR3i_BxRQ0dCVXeW9O3wo-BNVAsg2JUZtwG-LxaxbH8N-pHbZ2tDbxl8ZUA", "/docs/biology/2019-vallescolomer.pdf")
   , ("docs/history/1963-deroover-t", "/docs/history/1963-deroover-theriseanddeclineofthemedicibank.pdf")
   , ("docs/sociology/1974-martinson", "/docs/sociology/1974-martinson.pdf")
   , ("index.php", "/index")
   , ("docs/genetics/selection/1986-russell-likeengendringlike.pdf?fbclid=IwAR07oD2QUhcN2KKsW6T2cA7-2YMLirS-3p4BCgVc602jas1f8XXWa-Q84_g", "/docs/genetics/selection/1986-russell-likeengendringlike.pdf")
   , ("docs/genetics/selection/1986-russell-likeengendringlike.pdf?fbclid=IwAR3zscm9-DDBda9lKHEote3d3a-hvkWhpMUeEOqn8Tuh9BIvqdcnOTEpuek", "/docs/genetics/selection/1986-russell-likeengendringlike.pdf")
   , ("docs/iq/2015-roth.pdf).", "/docs/iq/2015-roth.pdf")
   , ("adrofinil", "/Modafinil")
   , ("DNM-arrestsl", "/DNM-arrests")
   , ("docs/ai/2019-anumanchipalli.pd", "/docs/ai/2019-anumanchipalli.pdf")
   , ("docs/genetics/selection/1986-russell-likeengendringlike.pdf?fbclid=IwAR2vSvMsVu2o7xLMHXHNh7EebLvhMkysRAaihcAHG6LWnaKV-ZHV9o1inX0", "/docs/genetics/selection/1986-russell-likeengendringlike.pdf")
   , ("docs/spacerepetition/1983-lee.pdf", "/docs/spacedrepetition/1983-lee.pdf")
   , ("Tanks]VentureBeat", "/Tanks")
   , ("docs/economics/1688-delavega-confusionofconfusions.pdf.", "/docs/economics/1688-delavega-confusionofconfusions.pdf")
   , ("cat-sense", "/Cat-Sense")
   , ("docs/ nature/2010-peen.pdfde", "/docs/ nature/2010-peen.pdf")
   , ("Pharmacology and Toxicology of _Nepeta cataria_ (Catmint) Species of Genus _Nepeta_: A Review", "/docs/catnip/2019-sharma.pdf")
   , ("Danbooru2017,", "/Danbooru2018")
   , ("docs/catnip/dx.doi.org/10.1016/j.mambio.2012.06.003", "/docs/catnip/2013-davoli.pdf")
   , ("death note", "/Death-Note-Anonymity")
   , ("De", "/Death-Note-Anonymity")
   , ("death-note-anonimity", "/Death-Note-Anonymity")
   , ("Death-note-Anonymity", "/Death-Note-Anonymity")
   , ("Death-Note-Anonymity3", "/Death-Note-Anonymity")
   , ("Death-Note-AnonymityIn?fbclid=IwAR2XiKn6SP9ZBer70Ew1PGbWQpDy7wp1mw498p6Sd81_LLoNIoBzx8BYbt4", "/Death-Note-Anonymity")
   , ("Death-Note-Script", "/Death-Note-script")
   , ("Death-Note-Scripts", "/Death-Note-script")
   , ("docs/2017-kirschner.pdf+español", "/docs/2017-kirschner.pdf")
   , ("docs/culture/2010-dobelli.PDF", "/docs/culture/2010-dobelli.pdf")
   , ("docs/culture/2010-dobelli.pdfAvoidNewsTowardsa?fbclid=IwAR1MO5RlQKXWADiwE__naJgvs7s45X32HYDzfu5n_Zve2KHNbCzI2Ju3eZM", "/docs/culture/2010-dobelli.pdf")
   , ("https://www.gwern.net/Hyperbolic-Time-Chamber", "/Hyperbolic-Time-Chamber")
   , ("123", "/index")
   , ("docs/dnb/2005-fregni.pdfsiamecca mcelree 1983", "/docs/dnb/2005-fregni.pdf")
   , ("docs/iq/smpy/2oo5-wallace.pdf", "/docs/iq/smpy/2005-wallace.pdf")
   , ("docs/japanese/1997-tsuzuki-tokyoacertaistyle.pdf", "/docs/japanese/1997-tsuzuki-tokyoacertainstyle.pdf")
   , ("docs/psychology/1The emergence and evolution of school psychology literature: A scientometric analysis from 1907 through 2014998-meehl.pdf", "/docs/psychology/1998-meehl.pdf")
   , ("docs/spacedrepitition/2004-stemarie.pdf", "/docs/spacedrepetition/2004-stemarie.pdf")
   , ("docs/iq/2006-dickerson.pdf&hl=en&sa=X&scisig=AAGBfm1OJnj05UmAZMQUo227O5qStyK7PA&nossl=1&oi=scholarr&ved=2ahUKEwivl7uu8vnjAhXVGs0KHVkcDyYQgAMoAHoECAgQAg&usg=AOvVaw18rJntSRjvFL48p6KdUdUj&cshid=1565494813549", "/docs/iq/2006-dickerson.pdf")
   , ("r/DarkNetMarkets/comments/30tudk/psa_5_reddit_accounts_subpoenaed_by_ice/index.html%3Futm_name%3DDarkNetMarkets", "/docs/sr/2015-03-30-gwern-redditsubpoena.html")
   , ("Spaced-repetition scv7000ss recepie", "/Spaced-repetition")
   , ("Bitcoin-isWorse-is-Better", "/Bitcoin-is-Worse-is-Better")
   , ("DNN-archives", "/DNM-archives")
   , ("docs/catnip/1930-kuo.pdfEibl-Eibesfeldt's solitary rats study", "/docs/catnip/1930-kuo.pdf")
   , ("docs/spacedrepitition.1994-hall.pdf", "/docs/spaced-repetition/1994-hall.pdf")
   , ("Terrorism-is-not-Effective.", "/Terrorism-is-not-Effective")
   , ("Death-Note-anonymity", "/Death-Note-Anonymity")
   , ("docs/1999-bradb", "/docs/ai/1999-bradbury-matrioshkabrains.pdf")
   , ("docs/iq/1993-vernonbiologicalapproachestudyhumanintelligence.pdf", "/docs/iq/1993-vernon-biologicalapproachestudyhumanintelligence.pdf")
   , ("featured", "/index")
   , ("LSD-microdosing.html", "/LSD-microdosing")
   , ("docs/economics/2006-anonymous-currintradingponzischeme.html", "/docs/economics/2006-james315-currintradingponzischeme.html")
   , ("docs/ai/2019-07-21", "/docs/ai/2019-07-21-taotehching-all-1ksamples.txt")
   , ("ABtesting", "/AB-testing")
   , ("docs/eva/2005-sawaragi-on-the-battlefield-of-superflat-subculture-and-art-in-postwar-japan", "/docs/eva/2005-sawaragi")
   , ("mistkaes", "/Mistakes")
   , ("docs/statistics/decision/1994-benter.pdf](https://www.gwern.net/docs/statistics/decision/1994-benter.pdf)", "/docs/statistics/decision/1994-benter.pdf")
   , ("docs/statistics/decision/1994-benter.pdf](https://www.gwern.net/docs/statistics/decision/1994-benter.pdf", "/docs/statistics/decision/1994-benter.pdf")
   , ("Resilient-Haskell-software", "/Resilient-Haskell-Software")
   , ("docs/sr/2019-04-22-deepdotweb-dnmlist.htm", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("agent", "/index")
   , ("android_asset/html/article-mobile.html", "/index")
   , ("face", "/Faces")
   , ("images/genetics/chi-dna.svg", "/images/icons/chi-dna.svg")
   , ("images/erowid.svg", "/images/icons/erowid.svg")
   , ("docs/genetics/heritable/2014-deryaku.pdf", "/docs/genetics/heritable/2014-deryakulu.pdf")
   , ("language", "/Language")
   , ("docs/ai/2019-winkler.pdf.", "/docs/ai/2019-winkler.pdf")
   , ("docs/iq/2007-strenze.pdfa", "/docs/iq/2007-strenze.pdf")
   , ("docs/catnip/1962-todd.pdf [Accessed 21 Aug. 2019].", "/docs/catnip/1962-todd.pdf")
   , ("docs/sr/2013-van-hout-pdf", "/docs/sr/2013-van-hout.pdf")
   , ("docs/sunkcosts/1972-trivers.[df", "/docs/sunkcosts/1972-trivers.pdf")
   , ("Greenlannews channels ratings", "/Greenland")
   , ("modifinil", "/Modafinil")
   , ("plugins/interwiki.hs", "/static/plugins/Interwiki.hs")
   , ("site.hs", "/hakyll.hs")
   , ("Spaced repetition Vermeer, Alex. Anki Essentials v1.1: The complete guide to remembering anything with Anki . Foggy Mountain Pass. Kindle-Version.", "/Spaced-repetition")
   , ("static/plugins/interwiki.hs", "/static/plugins/Interwiki.hs")
   , ("TANKS", "/Tanks")
   , ("docs/transhumanism/1990-regis-greatmambochicken.pdf", "/docs/transhumanism/1990-regis-greatmambochickenandthetranshumancondition.pdf")
   , ("docs/anime/2014-tamerlane-animeyearbyyear-2012.html", "/docs/anime/2014-tamerlane-animeyearbyyear-2001.html")
   , ("tags/newsletter).", "/tags/newsletter")
   , (" gwern", "/index")
   , ("Death-note-anonymity I y", "/Death-Note-anonymity")
   , ("docs/cukture/2912-russell.pdf", "/docs/culture/2012-russell.pdf")
   , ("docs/sr/2019-04-23-deepdotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("Spaced-repetition.log", "/Spaced-repetition")
   , ("tags/haskell", "/tags/Haskell")
   , ("tags/newsletter.", "/tags/newsletter")
   , ("Turin?fbclid=IwAR0z4c8HyrkAfrrjPo1iPirhQMPfnwNPz702wATzD0KGv4juZx7j34pnjRw", "/Turing-complete")
   , ("docs/psychology/2017-kirschner.pdf%3Chttps:/urldefense.proofpoint.com/v2/url?u=https-3A__www.gwern.net_docs_psychology_2017-2Dkirschner.pdf&d=DwMGaQ&c=vTCSeBKl9YZZHWJzz-zQUQ&r=NksmNiFKmjbXK3ezGHAsXhxdv5libDtFX85gzp0R0pw&m=D0F0E40PvqIZzhM2Ov5JCcnJYQ_rNPX7MoYFshqzcuM&s=a_Fc_OTEo95w-GpcwvsMV45l6oXGq2LFE-Eg08Tv27w&e=", "/docs/psychology/2017-kirschner.pdf")
   , ("docs/psychology/okcupid/yourlooksandyourinbox.html](https://www.gwern.net/docs/psychology/okcupid/yourlooksandyourinbox.html?fbclid=IwAR3STIttwvWrr9HAjjWeT275ts23qkxu-WdxcAo03pMmo30NpLyM6X_qkD4", "/docs/psychology/okcupid/yourlooksandyourinbox.html")
   , ("docs/1999-bradbury-matrioshkabrains.pdf&amp", "/docs/ai/1999-bradbury-matrioshkabrains.pdf")
   , ("nootropics/index.html", "/Nootropics")
   , ("docs/psychology/1995-westby.pdf](https://www.gwern.net/docs/psychology/1995-westby.pdf", "/docs/psychology/1995-westby.pdf")
   , (".../weexperimentonhumanbeings.html", "/docs/psychology/okcupid/weexperimentonhumanbeings.html")
   , (".../okcupid/yourlooksandyourinbox.html", "/docs/psychology/okcupid/yourlooksandyourinbox.html")
   , ("DNM-busts", "/DNM-arrests")
   , ("docs/smpy/1994-heller-competenceandresponsibility3rdconference.pdf", "/docs/iq/smpy/1994-heller-competenceandresponsibility3rdconference.pdf")
   , ("T3JkZXItc3", "/index")
   , ("Drug-heuristics arguements for flowers of Algernon", "/Drug-heuristics")
   , ("docs/bitcoin/pirateat40/SEC vs. pirateat40 1.pdf", "/docs/bitcoin/pirateat40/secvs.pirateat401.pdf")
   , ("docs/bitcoin/pirateat40/SEC vs. pirateat40 2.pdf", "/docs/bitcoin/pirateat40/secvs.pirateat402.pdf")
   ]
