[
   ("docs/nootropics/2010-nehling.pdf", "/docs/nootropics/2010-nehlig.pdf")
   , (" lithium", "/Lithium")
   , ("docs/dnb/2005-fregni.pdf>. Acesso em: 19 mar. 2019.", "/docs/dnb/2005-fregni.pdf")
   , ("docs/iq/2018-plomin", "/docs/iq/2018-plomin.pdf")
   , ("Longevit", "/Longevity")
   , ("docs/catnip/2011-detry.pdf", "/docs/history/2011-detry.pdf")
   , ("docs/conscientiousness/2007-bishopclark.pdf apa citation", "/docs/conscientiousness/2007-bishopclark.pdf")
   , (" oolong", "/Tea#oolong")
   , ("Danbooru2018 原文網址：https://kknews.cc/comic/4kpg92q.html", "/Danbooru2019#danbooru2018")
   , ("docs/melatonin /2014-boergers.pdf", "/docs/melatonin/2014-boergers.pdf")
   , ("docs/music-distraction/2005-Lesiuk.pdf", "/docs/music-distraction/2005-lesiuk.pdf")
   , ("docs/psychology/1952-asch", "/docs/psychology/1952-asch.pdf")
   , ("magnesium", "/nootropics/Magnesium")
   , ("Feed.hs", "https://github.com/jgm/gitit/blob/master/src/Network/Gitit/Feed.hs")
   , ("docs/sociology/2003-murray-humanaccomplishment.pdfwww.gwern.net", "/docs/sociology/2003-murray-humanaccomplishment.pdf")
   , ("Danbooru2018%20%E5%8E%9F%E6%96%87%E7%B6%B2%E5%9D%80%EF%BC%9Ahttps://kknews.cc/comic/4kpg92q.html", "/Danbooru2019#danbooru2018")
   , ("Danbooru2018%E4%BD%9C%E8%80%85%EF%BC%9Agrapeothttps://www.bilibili.com/read/cv2175924%E5%87%BA%E5%A4%84%EF%BC%9A%20bilibili", "/Danbooru2019#danbooru2018")
   , ("danbooru2019", "/Danbooru2019")
   , ("dgoogle scholarocs/genetics/correlation/1998-oconnor-2.pdfgoogle", "/docs/genetics/correlation/1998-oconnor-2.pdf")
   , ("docs/fiction/anonymous-nessusdnd.pdf%20https://akinokure.blogspot.com/index.html", "/docs/fiction/2015-mellonbread-dnd-nessus.pdf")
   , ("docs/gentetics/correlation/1987-kendler.pdf", "/docs/genetics/correlation/1987-kendler.pdf")
   , ("docs/genetics/correlation/1995-kendler.pdfhttps://www.ncbi.nlm.nih.gov/pmc/articles/PMC4677147/index.html","/docs/genetics/correlation/1995-kendler.pdf")
   , ("docs/iq/2014-carl.pdf&ved=2ahUKEwjqqa7Go7LhAhWMpIsKHeVrDW0QFjAAegQIAhAB&usg=AOvVaw1hTwJLlXBed-SoxCfn0zGa?fbclid=IwAR3FZlpEUvki5VKCahdcayUcOGSZzKupTj_pmmv0i-RxbrEVbnB9cKilQU8", "/docs/iq/2014-carl.pdf")
   , ("docs/iq/2015-st...", "/docs/iq/2015-strenze.pdf")
   , ("docs/iq/2019-alemany.pd", "/docs/iq/2019-alemany.pdf")
   , ("docs/sunkcosts/1984-bozerman.pdf", "/docs/sunkcosts/1984-bazerman.pdf")
   , ("docs/sunkcosts/1995-hoang", "/docs/sunkcosts/1995-hoang.pdf")
   , ("nootropics/Zeo", "/Zeo")
   , ("spaced-repetion", "/Spaced-repetition")
   , ("tags/bitcoin", "/tags/Bitcoin")
   , ("tags/dnb", "/tags/DNB")
   , ("tags/silk road", "/tags/Silk Road")
   , ("statistics/decision/1954-tukey.pdf", "/docs/statistics/decision/1954-tukey.pdf")
   , ("everything", "/Everything")
   , ("docs/dnb/2000- butzlaff.pdf", "/docs/dnb/2000-butzlaff.pdf")
   , ("docs/algernon/1995-rechtschaffen", "/docs/algernon/1995-rechtschaffen.pdf")
   , ("docs/genetics/correlations/2017-akiyama.pdf", "/docs/genetics/correlation/2017-akiyama.pdf")
   , ("docs/spacedrepetition/2012-muflax-dreamingofaworldundone.html", "/docs/spacedrepetition/2012-muflax-dreamingofaworldundone.html.maff")
   , ("Facesv", "/Faces")
   , ("docs/melatonin/2014-boergers.pdf. Times.pdf", "/docs/melatonin/2014-boergers.pdf")
   , ("TWDNEthiswaifudoesnotexist.net", "/TWDNE")
   , ("thiswaifudoesntexist/index.html", "https://www.thiswaifudoesnotexist.net/")
   , ("Coin-Flip", "/Coin-flip")
   , ("docs/anime/danbooru2017", "/Danbooru2019#danbooru2018")
   , ("docs/melatonin/2014-boergers.pdf.Times.pdf", "/docs/melatonin/2014-boergers.pdf")
   , ("docs/melatoin/2014-boergers.pdf", "/docs/melatonin/2014-boergers.pdf")
   , ("docs/nature/2010-peen.pdf.", "/docs/nature/2010-peen.pdf")
   , ("Embryo selection.", "/Embryo-selection")
   , ("google-shutdowns", "/Google-shutdowns")
   , ("Melatonincd", "/Melatonin")
   , ("modafnil", "/Modafinil")
   , ("docs/japanese/1940-nippongakujutsushinkokan-manyoshu.pdf", "/docs/japanese/1940-nippongakujutsushinkokai-manyoshu.pdf")
   , ("docs/music-distraction/2014-perham.pdf .", "/docs/music-distraction/2014-perham.pdf")
   , ("docs/spacedrepetition/1986-goode.pdf%EF%BB%BF", "/docs/spacedrepetition/1986-goode.pdf")
   , ("statics/css/default.css", "/static/css/default.css")
   , ("Blackmarket survival", "/DNM-survival")
   , ("caffeine", "/zeo/Caffeine")
   , ("complment", "/Complement")
   , ("Danbooru2015", "/Danbooru2019#danbooru2018")
   , ("docs/economics/1968-thomas.pdf)", "/docs/economics/1968-thomas.pdf")
   , ("docs/genetics/editing/2017-scheufele.pdf.", "/docs/genetics/editing/2017-scheufele.pdf")
   , ("docs/longevity/2019-vrselja.pdf&ved=2ahUKEwjoz72F69fhAhWRDewKHevaCWMQFjAAegQIAxAB&usg=AOvVaw2p7iJrPDjEvKUUXtEmqSCG&cshid=1555528546459", "/docs/longevity/2019-vrselja.pdf")
   , ("docs/nature/2010-peen.pdf - The current status of urban-rural differencesin psychiatric disorders", "/docs/nature/2010-peen.pdf")
   , ("docs/spacedrepetition/2007-rohrer.pdf%EF%BB%BF", "/docs/spacedrepetition/2007-rohrer.pdf")
   , ("docspsychology/1952-asch.pdf", "/docs/psychology/1952-asch.pdf")
   , ("lsdmicrodosing", "/LSD-microdosing")
   , ("newsletter/2014/0l01", "/newsletter/2014/01")
   , ("newsletter/2014/0ll1", "/newsletter/2014/01")
   , ("Superrationa", "/docs/xrisks/1985-hofstadter")
   , ("r/DarkNetMarkets/comments/30tudk/psa_5_reddit_accounts_subpoenaed_by_ice/index.html?utm_name=DarkNetMarkets", "/docs/sr/2015-03-30-gwern-redditsubpoena.html")
   , ("Aboutpage", "/About.page")
   , ("docs/iq/1966-shuey-thetestingofnegrointelligencevol1.pdf)", "/docs/iq/1966-shuey-thetestingofnegrointelligencevol1.pdf")
   , ("donate", "https://www.patreon.com/gwern")
   , ("Danbooru2018原文網址：https://kknews.cc/zh-tw/comic/3a3ap4a.html", "/Danbooru2019#danbooru2018")
   , ("dics/dnb/2000-vaughn.pdf", "/docs/dnb/2000-vaughn.pdf")
   , ("docs/ai/2019-anumanchipalli.pdf---", "/docs/ai/2019-anumanchipalli.pdf")
   , ("docs/ai/2019-anumanchipalli.pdf.", "/docs/ai/2019-anumanchipalli.pdf")
   , ("docs/borges/1936-borgesthetranslatorsofthethousandandonenights.pdf", "docs/borges/1936-borges-thetranslatorsofthethousandandonenights.pdf")
   , ("docs/conscientiousness/1994-krueger.", "/docs/conscientiousness/1994-krueger.pdf")
   , ("docs/eva/null", "/docs/eva/index.html")
   , ("docs/iq/2018-rindermann.pdf (https://www.gwern.net/docs/iq/2018-rindermann.pdf", "/docs/iq/2018-rindermann.pdf")
   , ("docs/iq/2018-rindermann.pdf (https://www.gwern.net/docs/iq/2018-rindermann.pdf)", "/docs/iq/2018-rindermann.pdf")
   , ("docs/japanese/1997-tsuzuki-tokyoacerta?fbclid=IwAR3VGSgGB_oFbkju-ydkbfUJ_5sNI49QqRxe_zZB162YE-ytkRsi-hYS2wc", "/docs/japanese/1997-tsuzuki-tokyoacertainstyle.pdf")
   , ("docs/modafinil/1988-bastuji.pdf.", "/docs/modafinil/1988-bastuji.pdf")
   , ("docs/music-dpurnell webb and speelmanistraction/1989-salame.pdf", "/docs/music-distraction/1989-salame.pdf")
   , ("docs/psychology/1952-asch.pd", "/docs/psychology/1952-asch.pdf")
   , ("FAces", "/Faces")
   , ("Self-decrypting-file", "/Self-decrypting-files")
   , ("eveything", "/Everything")
   , ("Eveything", "/Everything")
   , ("ieverything", "/Everything")
   , ("docs/algernon/2006-harris.pdf)", "/docs/algernon/2006-harris.pdf")
   , ("docs/spaced repetition/1987-bahrick.pdf", "/docs/spacedrepetition/1987-bahrick.pdf")
   , ("docs/spacedrepetition/1987- bahrick.pdf", "/docs/spacedrepetition/1987-bahrick.pdf")
   , ("docs/spacedrepetition/1987-%20bahrick.pdf", "/docs/spacedrepetition/1987-bahrick.pdf")
   , ("Tasks", "/Tanks")
   , ("Danbooru2018 原文網址：https://mttmp.com/cijjxnk.html", "/Danbooru2019#danbooru2018")
   , ("dnm-archive", "/DNM-archives")
   , ("docs/20081003-nakamoto-bitcoindraft.pd", "/docs/bitcoin/20081003-nakamoto-bitcoindraft.pdf")
   , ("docs/ai/2019-anumanchipalli.pdf 原文網址：https://kknews.cc/science/66zoyvl.html", "/docs/ai/2019-anumanchipalli.pdf")
   , ("docs/genetics/selction/1977-todd.pdf", "/docs/genetics/selection/1977-todd.pdf")
   , ("docs/iq/2009-richwine.pdf&ved=2ahUKEwj0tf768fPhAhXaFjQIHUY6DHAQFjAEegQIBBAB&usg=AOvVaw27jr39IWA2u_bQbOXYJukN?fbclid=IwAR2d_TuC8KCmP1K4rAqzN7q2ST47TEBffYzz5m_hIaCyLqoatCkO4NXOMuo", "/docs/iq/2009-richwine.pdf")
   , ("docs/melatonin/2009-burkhart.pdf.", "/docs/melatonin/2009-burkhart.pdf")
   , ("docs/music-distraction/2005-lesiuk.pdf&ved=2ahUKEwiXjYD2p4LiAhW8HjQIHUKUBcoQFjAAegQIAxAB&usg=AOvVaw0Gg776a4B-kua4OH8kBpEW", "/docs/music-distraction/2005-lesiuk.pdf")
   , ("docs/music-distraction/2011-huang.pdfhttps://scholar.google.com.mx/scholar?hl=es&as_sdt=0,5&q=classical+music+decibels+concentration&btnG=", "/docs/music-distraction/2011-huang.pdf")
   , ("docs/rl/2016-graves.pd", "/docs/rl/2016-graves.pdf")
   , ("images/mooreslaw-marketvolumelaw", "/images/mooreslaw-marketvolumelaw.png")
   , ("Silk-Road.txt", "/Silk-Road.page")
   , ("static/font/SourceSansPro-BASIC-BlackItalic.ttf'", "/static/font/SourceSansPro-BASIC-BlackItalic.ttf")
   , ("writings/changes", "/Changelog")
   , ("docs/ai/2019/anumanchipalli.pdf", "/docs/ai/2019-anumanchipalli.pdf")
   , ("index l theanine + caffeine", "/index")
   , ("docs/music-distraction/1989-salame", "/docs/music-distraction/1989-salame.pdf")
   , ("Docs/Music-Distraction/2002-Hallam.pdf", "/docs/music-distraction/2002-hallam.pdf")
   , ("Drug-heuristic", "/Drug-heuristics")
   , ("docs/sr/docs/sr/2015-03-18-the_avid-evolutionmarketbackground-cardingforumsponzischemesle.html", "/docs/sr/2015-03-18-the_avid-evolutionmarketbackground-cardingforumsponzischemesle.html")
   , ("docs/sr/docs/sr/2014-01-02-deepdotweb-flomarketexitscam.html", "/docs/sr/2014-01-02-deepdotweb-flomarketexitscam.html")
   , ("docs/sr/docs/sr/2014-01-09-deepdotweb-flomarketinterview.html", "/docs/sr/2014-01-09-deepdotweb-flomarketinterview.html")
   , ("docs/sr/docs/sr/2014-01-23-deepdotweb-outlawmarketinterview.html", "/docs/sr/2014-01-23-deepdotweb-outlawmarketinterview.html")
   , ("docs/sr/docs/sr/2014-01-27-deepdotweb-pandoramoderatorhack.html", "/docs/sr/2014-01-27-deepdotweb-pandoramoderatorhack.html")
   , ("docs/sr/docs/sr/2014-02-12-deepdotweb-theutopiabust.html", "/docs/sr/2014-02-12-deepdotweb-theutopiabust.html")
   , ("docs/sr/docs/sr/2014-02-21-deepdotweb-darknetnationinterview.html", "/docs/sr/2014-02-21-deepdotweb-darknetnationinterview.html")
   , ("docs/sr/docs/sr/2014-03-12-deepdotweb-hansamarketdoxxed.html", "/docs/sr/2014-03-12-deepdotweb-hansamarketdoxxed.html")
   , ("docs/sr/docs/sr/2014-03-18-deepdotweb-evolutionexitscam130kbtclost.html", "/docs/sr/2014-03-18-deepdotweb-evolutionexitscam130kbtclost.html")
   , ("docs/sr/docs/sr/2014-03-20-deepdotweb-pandorahacked.html", "/docs/sr/2014-03-20-deepdotweb-pandorahacked.html")
   , ("docs/sr/docs/sr/2014-04-08-deepdotweb-therealdeal.html", "/docs/sr/2014-04-08-deepdotweb-therealdeal.html")
   , ("docs/sr/docs/sr/2014-04-19-deepdotweb-1776announcement.html", "/docs/sr/2014-04-19-deepdotweb-1776announcement.html")
   , ("docs/sr/docs/sr/2014-08-01-deepdotweb-outlawmarketclosed.html", "/docs/sr/2014-08-01-deepdotweb-outlawmarketclosed.html")
   , ("docs/sr/docs/sr/2014-09-23-deepdotweb-newdetailsabouttheutopiamarketplacebust.html", "/docs/sr/2014-09-23-deepdotweb-newdetailsabouttheutopiamarketplacebust.html")
   , ("docs/sr/docs/sr/2014-11-09-deepdotweb-pedofunding.html", "/docs/sr/2014-11-09-deepdotweb-pedofunding.html")
   , ("docs/sr/docs/sr/2014-11-11-deepdotweb-hydraadminarrest.html", "/docs/sr/2014-11-11-deepdotweb-hydraadminarrest.html")
   , ("docs/sr/docs/sr/2015-01-14-deepdotweb-israeliteenarrested.html", "/docs/sr/2015-01-14-deepdotweb-israeliteenarrested.html")
   , ("docs/sr/docs/sr/2015-05-12-deepdotweb-translationhuntunderway.html", "/docs/sr/2015-05-12-deepdotweb-translationhuntunderway.html")
   , ("docs/sr/docs/sr/2015-06-02-deepdotweb-poseidonmarketdoxxed.html", "/docs/sr/2015-06-02-deepdotweb-poseidonmarketdoxxed.html")
   , ("docs/sr/docs/sr/2015-06-04-deepdotweb-utopiamarketadmincosanostra.html", "/docs/sr/2015-06-04-deepdotweb-utopiamarketadmincosanostra.html")
   , ("docs/sr/docs/sr/2015-07-07-deepdotweb-agorabansguns.html", "/docs/sr/2015-07-07-deepdotweb-agorabansguns.html")
   , ("docs/sr/docs/sr/2015-07-16-deepdotweb-pedofundingdashcoin.html", "/docs/sr/2015-07-16-deepdotweb-pedofundingdashcoin.html")
   , ("docs/sr/docs/sr/2015-08-09-deepdotweb-eastindiacompanyhack.html", "/docs/sr/2015-08-09-deepdotweb-eastindiacompanyhack.html")
   , ("docs/sr/docs/sr/2015-08-10-deepdotweb-thestoryofanunluckyitaliancyberpusher.html", "/docs/sr/2015-08-10-deepdotweb-thestoryofanunluckyitaliancyberpusher.html")
   , ("docs/sr/docs/sr/2015-09-05-deepdotweb-darknetvendorsentencedto8years.html", "/docs/sr/2015-09-05-deepdotweb-darknetvendorsentencedto8years.html")
   , ("docs/sr/docs/sr/2015-11-29-deepdotweb-theidealisticmotivesbehindvalhalla.html", "/docs/sr/2015-11-29-deepdotweb-theidealisticmotivesbehindvalhalla.html")
   , ("docs/sr/docs/sr/2016-02-09-deepdotweb-horticulturalstudentinperth.html", "/docs/sr/2016-02-09-deepdotweb-horticulturalstudentinperth.html")
   , ("docs/sr/docs/sr/2016-08-12-deepdotweb-fedsindicttwoalphabayvendors.html", "/docs/sr/2016-08-12-deepdotweb-fedsindicttwoalphabayvendors.html")
   , ("docs/sr/docs/sr/2016-09-21-deepdotweb-alaskanmanarrested.html", "/docs/sr/2016-09-21-deepdotweb-alaskanmanarrested.html")
   , ("docs/sr/docs/sr/2016-11-04-deepdotweb-belgianvendorarrestedinsufficientpostage.html", "/docs/sr/2016-11-04-deepdotweb-belgianvendorarrestedinsufficientpostage.html")
   , ("docs/sr/docs/sr/2017-04-07-deepdotweb-afterhoursentenced.html", "/docs/sr/2017-04-07-deepdotweb-afterhoursentenced.html")
   , ("docs/sr/docs/sr/2019-01-24-deepdotweb-dnmlistchangelog.html", "/docs/sr/2019-01-24-deepdotweb-dnmlistchangelog.html")
   , ("docs/sr/2019-01-24-deepdotweb-dnmlistchanghydraruzxpnew4afelog.html", "/docs/sr/2019-01-24-deepdotweb-dnmlistchangelog.html")
   , ("docs/sr/docs/sr/2019-04-22-deepdotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/2019-06-??-deepdotweb-dnmlist.html=", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("Drug-heurist", "/Drug-heuristics")
   , ("Facesより)", "/Faces")
   , ("market/item/stilnoct-swedish-pharmacy-10mg-01d3b46686", "/tags/Silk%20Road")
   , ("docs/anime/2013-arudou.pdf.", "/docs/anime/2013-arudou.pdf")
   , ("docs/iq/1996-gendreau.Gendreau & Swartz (2009) demonstrated there are more effective outcomes if intervention programmes include the elements of risk, need and responsivity, in comparison to alternative", "/docs/iq/1996-gendreau.pdf")
   , ("docs/iq/1996-gendreau.", "/docs/iq/1996-gendreau.pdf")
   , ("does/statictics/1973-meshalkin-collectionofproblemsinprobabilitytheony.pdf", "/docs/statistics/1973-meshalkin-collectionofproblemsinprobabilitytheory.pdf")
   , ("Mail-deliveryusps", "/Mail-delivery")
   , ("docs/sociology/1997-rossi", "/docs/sociology/1987-rossi")
   , ("docs/ai/2019-05-13-gpt2-poetry-335m-5000samples.txt", "/docs/ai/2019-05-13-gpt2-poetry-345m-5000samples.txt")
   , ("modus", "/Modus")
   , ("modus-ponens", "/Modus")
   , ("modus-tollens", "/Modus")
   , ("Modus-ponens", "/Modus")
   , ("Modus-tollens", "/Modus")
   , ("ai/2019-05-13-gpt2-poetry-345m-5000samples.txt", "/docs/ai/2019-05-13-gpt2-poetry-345m-5000samples.txt")
   , ("docs/psychology/ 1952-asch.pdf", "/docs/psychology/1952-asch.pdf")
   , ("docs/radiance/198 @BOOK {chesney, |4-berger.pdf", "/docs/radiance/1984-berger.pdf")
   , ("docs/statistics/2015-franco.pdf http:/van Erp, S., Verhagen, J., Grasman, R., & Wagenmakers,E. (2013). Estimates of Between-Study Heterogeneityfor 705 Meta-Analyses Reported in PsychologicalBulletin From 1990-2013.journals.sagepub.com/doi/10.1177/1948550615598377", "/docs/statistics/2015-franco.pdf")
   , ("...longevity/2014-bannister.pdf", "/docs/longevity/2014-bannister.pdf")
   , ("DNM archives.", "/DNM-archives")
   , ("docs/economics/1927-ramsey.pd", "/docs/economics/1927-ramsey.pdf")
   , ("docs/genetics/editing/2019-south.", "/docs/genetics/editing/2019-south.pdf")
   , ("docs/iq/2016-boccio.pdf<", "/docs/iq/2016-boccio.pdf")
   , ("docs/nature/2010-peen.pd", "/docs/nature/2010-peen.pdf")
   , ("docs/psychology/1977-ross.pdf.", "/docs/psychology/1977-ross.pdf")
   , ("usesthis", "/Links#uses-this")
   , ("research", "/Research-criticism")
   , ("Research", "/Research-criticism")
   , ("Research-critic", "/Research-criticism")
   , ("Research-critique", "/Research-criticism")
   , ("reseach", "/Research-criticism")
   , ("research-criticism", "/Research-criticism")
   , ("docs/genetics/heritable/1967-goslin-teachersandtesting.pdf (teachers and ability 1967)", "/docs/genetics/heritable/1967-goslin-teachersandtesting.pdf")
   , (" docs/genetics/heritable/1967-goslin-teachersandtesting.pdf", "/docs/genetics/heritable/1967-goslin-teachersandtesting.pdf")
   , ("docs/music-distraction/2011-huang.pd", "/docs/music-distraction/2011-huang.pdf")
   , ("GPT", "/GPT-2")
   , ("GPT-", "/GPT-2")
   , ("GPT2", "/GPT-2")
   , ("Gpt-2", "/GPT-2")
   , ("Gpt2", "/GPT-2")
   , ("gpt", "/GPT-2")
   , ("gpt-", "/GPT-2")
   , ("gpt-2", "/GPT-2")
   , ("gpt2", "/GPT-2")
   , ("GPT-1", "/GPT-2")
   , ("mofafinil", "/Modafinil")
   , ("terrorism-is-not-effective", "/Terrorism-is-not-Effective")
   , ("terrorism", "/Terrorism-is-not-about-Terror")
   , ("spaced reoetition", "/Spaced-repetition")
   , ("Blackmailfail", "/Blackmail")
   , ("docs/bitcoin/20081003-nakamoto", "/docs/bitcoin/20081003-nakamoto-bitcoindraft.pdf")
   , ("docs/borges/1936-borges-ahistoryofeternity.pd", "/docs/borges/1936-borges-ahistoryofeternity.pdf")
   , ("docs/dnb/2003-jaeggi.pdf)", "/docs/dnb/2003-jaeggi.pdf")
   , ("docs/genetics/heritable/2019-barlow.pd", "/docs/genetics/heritable/2019-barlow.pdf")
   , ("docs/predictions/2001-armstrong-principlesforecasting", "/docs/predictions/2001-armstrong-principlesforecasting.pdf")
   , ("About exit scam", "/About")
   , ("docs/dnb/2003-jaeggi.pdf /index.html", "/docs/dnb/2003-jaeggi.pdf")
   , ("docs/genetics/heritable/2019-barlow.pdf:", "/docs/genetics/heritable/2019-barlow.pdf")
   , ("Clones", "/Clone")
   , ("Dog-clone", "/Clone")
   , ("dog-clone", "/Clone")
   , ("Dog-cloning", "/Clone")
   , ("dog-cloning", "/Clone")
   , ("docs/dnb/2000-vaughan.pdf. Accessed 30 May 2019", "/docs/dnb/2000-vaughan.pdf")
   , ("docs/dnb/2005-ackerman.pdf.", "/docs/dnb/2005-ackerman.pdf")
   , ("docs/eva/2010-crchttps://www.gwern.net/docs/eva/2010-crc", "/docs/eva/2010-crc")
   , ("website", "/index")
   , ("docs/borges/1947-borges-anewrefutationoftime.pdf.", "/docs/borges/1947-borges-anewrefutationoftime.pdf")
   , ("docs/borges/1977-borges-blindness.pdf.", "/docs/borges/1977-borges-blindness.pdf")
   , ("docs/genetics/correlation/2019-baselmans", "/docs/genetics/correlation/2019-baselmans.pdf")
   , ("Everything - everything is correlated", "/Everything")
   , ("Statistic=", "/Statistical-notes")
   , ("i", "/iq")
   , ("dfoods to.redce dihetaocs/economics/2011-ziobrowski.pdf", "/docs/economics/2011-ziobrowski.pdf")
   , ("About)", "/About")
   , ("doc/statistics/decision/1939-pearson.pdf", "/docs/statistics/decision/1939-pearson.pdf")
   , ("docs/bitcoin/1963-brown-pacioloonaccou...", "/docs/bitcoin/1963-brown-pacioloonaccounting.pdf")
   , ("index open", "/index")
   , ("Linkshttps://www.gwern.net/Mistakes", "/Links")
   , ("newsleter", "/tags/newsletter")
   , ("RNNmetadata", "/RNN-metadata")
   , ("Stress", "/On-Stress")
   , ("socks", "/Socks")
   , ("sock", "/Socks")
   , ("Sock", "/Socks")
   , ("statistics/bias/1975-rosenthal-experimenterexpectancyeffects.pdf", "/docs/statistics/bias/1976-rosenthal-experimenterexpectancyeffects.pdf")
   , ("docs/longevity/2017-kirkland", "/docs/longevity/2017-kirkland.pdf")
   , ("docs/psychology/1941-cleckley-maskofsanity.pdfCleckley, H. (1976). The mask of sanity: An attempt to clarify some issues about the so-called psychopathic personality (5th ed.). St. Louis, MO: Mosby", "/docs/psychology/1941-cleckley-maskofsanity.pdf")
   , ("docs/sociology/2003-murray-humanaccomplishment.pdf&ved=2ahUKEwj-rLfEv9_iAhWDjYsKHd3AA-MQFjALegQIARAB&usg=AOvVaw3AB3oisqc2OBZbyj2hKWJL&cshid=1560189726029?fbclid=IwAR2eQCXqidkRPhBRZTOc8ewvrBIWS0vao9TxwGPqbQL4EkKaKk_FlXiSa6w", "/docs/sociology/2003-murray-humanaccomplishment.pdf")
   , ("Nootropicsmixing up graphic symbols", "/Nootropics")
   , ("research-bounties", "/Fulltext")
   , ("Research-bounties", "/Fulltext")
   , ("Research-Bounties", "/Fulltext")
   , ("research-Bounties", "/Fulltext")
   , ("docs/statistics/meta-analysis/2004-hunterschmidt-methodsofmetaanalysis.pdf<br><br><br>Much", "/docs/statistics/meta-analysis/2004-hunterschmidt-methodsofmetaanalysis.pdf")
   , ("docs/borges/1951-borges-pascal.pdf", "/docs/borges/1951-borges-pascalssphere.pdf")
   , (".../psychology/.../1980-hartley-thepsychologyofwrittencommunication", "/docs/psychology/writing/1980-hartley-thepsychologyofwrittencommunication.pdf")
   , (" author", "/Links")
   , ("docs/cs/1982-perlis.pdf'", "/docs/cs/1982-perlis.pdf")
   , ("docs/iq/1963-rosenthal.pdf&ved=2ahUKEwjx-dmt5eviAhUBmlkKHWYkBFcQFjAHegQIARAB&usg=AOvVaw10-03O1gOPuyuQ7JajfGzY", "/docs/iq/1963-rosenthal.pdf")
   , ("docs/statistics/decisions", "/docs/statistics/decision/index.html")
   , ("FTanks", "/Tanks")
   , ("timing", "/Timing")
   , ("Media-Lab", "/Timing")
   , ("Media-lab", "/Timing")
   , ("media-lab", "/Timing")
   , ("Tining", "/Timing")
   , ("Timning", "/Timing")
   , ("bookshelf", "/Books")
   , ("docs/culture/2010-dobelli.pdf&ved=2ahUKEwjegNGJ_PXiAhXBk4sKHe7zC_YQFjAAegQIARAB&usg=AOvVaw2tAxL_d3sJEtug1zIGDq87&cshid=1560962048169", "/docs/culture/2010-dobelli.pdf")
   , ("About.site", "/About#site")
   , ("docs/iq/2007-strenze.pdf&ved=2ahUKEwjVlbnIx_PiAhWs-ioKHUYzD3oQFjAAegQIAhAB&usg=AOvVaw1qc8H3nnM1YwkEeYDoklG1", "/docs/iq/2007-strenze.pdf")
   , ("modafin", "/Modafinil")
   , ("docs/statistics/peerreview/2017-goldestein.pdf", "/docs/statistics/peerreview/2017-goldstein.pdf")
   , ("docs/genetics/correlation/2019-wojcik.pdfpre-check your script", "/docs/genetics/correlation/2019-wojcik.pdf")
   , ("docs/genetics/heritable/1984-buss-temperamentearlydevelopingpersonalitytraits.pdf)", "/docs/genetics/heritable/1984-buss-temperamentearlydevelopingpersonalitytraits.pdf)")
   , ("docs/iq/2014-carl.pd", "/docs/iq/2014-carl.pdf")
   , ("docs/longevity/2014-bannister.pdf.", "/docs/longevity/2014-bannister.pdf")
   , ("account/profile/05abde47fcf35cd033ff12b9254bf3a0/4", "/index")
   , ("dos/math/2009-sinclair.pd", "/docs/math/2009-sinclair.pdf")
   , ("Facesより", "/Faces")
   , ("docs/iq/1938-cattell.pdf)", "/docs/iq/1938-cattell.pdf")
   , ("docs/math/2009-sinclair-pdf", "/docs/math/2009-sinclair.pdf")
   , ("acd123459879.lkj?vf=vfd", "/index")
   , ("docs/iq/2014-hyde.pdf.", "/docs/iq/2014-hyde.pdf")
   , ("dozi8hz/jfiops.sxc", "/index")
   , ("dtyu<script>2644.igr?vf=jky", "/index")
   , ("jkstatus", "/index")
   , ("sgty76hu3f09", "/index")
   , ("docs/psychology/1996-rachman.pdf",  "/docs/psychology/1966-rachman.pdf")
   , ("dnm survival", "/DNM-survival")
   , ("docs/genetics/heritable/2018-khera.pdf**==?tdsourcetag=s_pctim_aiomsg", "/docs/genetics/heritable/2018-khera.pdf")
   , ("docs/music-distraction/2005-lesiu", "/docs/music-distraction/2005-lesiuk.pdf")
   , ("docs/sr/2019-04-22-deepweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/2019-04-22deepweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/2019-04022deepweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/null", "/docs/sr/index.html")
   , ("docs/catnip/3000-turner-thedomesticcat.pdf", "/docs/catnip/2000-turner-thedomesticcat.pdf")
   , ("docs/iq/2013-lynn.pdf (old data)", "/docs/iq/2013-lynn.pdf")
   , ("docs/spacedrepetition/1939-spitzer", "/docs/spacedrepetition/1939-spitzer.pdf")
   , ("Spaced-repetition for", "/Spaced-repetition")
   , ("blackmarket archives", "/DNM-archives")
   , ("docs/anime/2014-tamer...", "/docs/anime/2014-tamerlane-animeyearbyyear-2001.html")
   , ("Charity", "/Charity-is-not-about-helping")
   , ("docs/genetics/heritable/1966-heston", "/docs/genetics/heritable/1966-heston.pdf")
   , ("docs/genetics/selection/2000-kaback.pdf)", "/docs/genetics/selection/2000-kaback.pdf")
   , ("docs/japanese/2001-debary-sourcesofjapanesetradition", "/docs/japanese/2001-debary-sourcesofjapanesetradition.pdf")
   , ("docs/statistics/decision/1986-stephens-foragingtheory.pdfAnts at work: How an insect society is organized.", "/docs/statistics/decision/1986-stephens-foragingtheory.pdf")
   , ("images/rl/2018-metz-table1-metalearni=", "/images/rl/2018-metz-table1-metalearningparadigms.png")
   , ("dambooru2018", "/Danbooru2019#danbooru2018")
   , ("Magnesium", "/nootropics/Magnesium")
   , ("docs/iq/2019-jiang.pdf?origin_team=T542U849X", "/docs/iq/2019-jiang.pdf")
   , ("docs/sr/2019-04-22-deepdotweb-dnmlist.htmlxme", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , (" spaced repetition", "/Spaced-repetition")
   , ("account/profile/05abde47fcf35cd033ff12b9254bf3a0/2", "/tags/Silk%20Road")
   , ("black-market", "/tags/Silk%20Road")
   , ("Danbooru2018原文網址：https://kknews.cc/comic/3a3ap4a.html", "/Danbooru2019#danbooru2018")
   , ("Danbooru2018 原文網址：https://kknews.cc/comic/3a3ap4a.html", "/Danbooru2019#danbooru2018")
   , ("docs/psychology/2006-feist.pdfhttps://mail.ru", "/docs/psychology/2006-feist.pdf")
   , ("docs/psychology/okcupid/yourlooksandyourinbox", "/docs/psychology/okcupid/yourlooksandyourinbox.html")
   , ("docs/spacedrepetition/2012-mcdaniel.pdf\"Using quizzes to enhance summative-assessment performance in a web-based class: An experimental study\"", "/docs/spacedrepetition/2012-mcdaniel.pdf")
   , ("docs/sr/caligirl-profile.ht", "/wiki/docs/sr/caligirl-profile.htm")
   , ("market/item/amfetamin-100gram-klet-dunder-17d57ed2a8", "/tags/Silk%20Road")
   , ("market/item/weed-hawaiian-snow-4-gram-f408fb748c", "/tags/Silk%20Road")
   , ("newsletter/2019/june", "/newsletter/2019/06")
   , ("zeo/Magnesium", "/zeo/ZMA")
   , ("docs/iq/smpy/1986-renzulli systemsandmodelsforprogramsforgiftedtalented.pdf", "/docs/iq/smpy/1986-renzulli-systemsandmodelsforprogramsforgiftedtalented.pdf")
   , ("Faces quilt", "/Faces#applications")
   , ("style.css", "/static/css/default.css")
   , ("docs/biology/2019-vallescolomer.pdf&hl=pt-BR&sa=X&scisig=AAGBfm2-09J4Xc9FHgHQ-x3-Pv8E6Gb_1g&nossl=1&oi=scholarr?fbclid=IwAR3i_BxRQ0dCVXeW9O3wo-BNVAsg2JUZtwG-LxaxbH8N-pHbZ2tDbxl8ZUA", "/docs/biology/2019-vallescolomer.pdf")
   , ("docs/history/1963-deroover-t", "/docs/history/1963-deroover-theriseanddeclineofthemedicibank.pdf")
   , ("docs/sociology/1974-martinson", "/docs/sociology/1974-martinson.pdf")
   , ("index.php", "/index")
   , ("docs/genetics/selection/1986-russell-likeengendringlike.pdf?fbclid=IwAR07oD2QUhcN2KKsW6T2cA7-2YMLirS-3p4BCgVc602jas1f8XXWa-Q84_g", "/docs/genetics/selection/1986-russell-likeengendringlike.pdf")
   , ("docs/genetics/selection/1986-russell-likeengendringlike.pdf?fbclid=IwAR3zscm9-DDBda9lKHEote3d3a-hvkWhpMUeEOqn8Tuh9BIvqdcnOTEpuek", "/docs/genetics/selection/1986-russell-likeengendringlike.pdf")
   , ("docs/iq/2015-roth.pdf).", "/docs/iq/2015-roth.pdf")
   , ("adrofinil", "/Modafinil")
   , ("DNM-arrestsl", "/DNM-arrests")
   , ("docs/ai/2019-anumanchipalli.pd", "/docs/ai/2019-anumanchipalli.pdf")
   , ("docs/genetics/selection/1986-russell-likeengendringlike.pdf?fbclid=IwAR2vSvMsVu2o7xLMHXHNh7EebLvhMkysRAaihcAHG6LWnaKV-ZHV9o1inX0", "/docs/genetics/selection/1986-russell-likeengendringlike.pdf")
   , ("docs/spacerepetition/1983-lee.pdf", "/docs/spacedrepetition/1983-lee.pdf")
   , ("Tanks]VentureBeat", "/Tanks")
   , ("docs/economics/1688-delavega-confusionofconfusions.pdf.", "/docs/economics/1688-delavega-confusionofconfusions.pdf")
   , ("cat-sense", "/Cat-Sense")
   , ("docs/ nature/2010-peen.pdfde", "/docs/ nature/2010-peen.pdf")
   , ("Pharmacology and Toxicology of _Nepeta cataria_ (Catmint) Species of Genus _Nepeta_: A Review", "/docs/catnip/2019-sharma.pdf")
   , ("Danbooru2017,", "/Danbooru2019#danbooru2018")
   , ("docs/catnip/dx.doi.org/10.1016/j.mambio.2012.06.003", "/docs/catnip/2013-davoli.pdf")
   , ("death note", "/Death-Note-Anonymity")
   , ("De", "/Death-Note-Anonymity")
   , ("death-note-anonimity", "/Death-Note-Anonymity")
   , ("Death-note-Anonymity", "/Death-Note-Anonymity")
   , ("Death-Note-Anonymity3", "/Death-Note-Anonymity")
   , ("Death-Note-AnonymityIn?fbclid=IwAR2XiKn6SP9ZBer70Ew1PGbWQpDy7wp1mw498p6Sd81_LLoNIoBzx8BYbt4", "/Death-Note-Anonymity")
   , ("Death-Note-Script", "/Death-Note-script")
   , ("Death-Note-Scripts", "/Death-Note-script")
   , ("docs/2017-kirschner.pdf+español", "/docs/2017-kirschner.pdf")
   , ("docs/culture/2010-dobelli.PDF", "/docs/culture/2010-dobelli.pdf")
   , ("docs/culture/2010-dobelli.pdfAvoidNewsTowardsa?fbclid=IwAR1MO5RlQKXWADiwE__naJgvs7s45X32HYDzfu5n_Zve2KHNbCzI2Ju3eZM", "/docs/culture/2010-dobelli.pdf")
   , ("https://www.gwern.net/Hyperbolic-Time-Chamber", "/Hyperbolic-Time-Chamber")
   , ("123", "/index")
   , ("docs/dnb/2005-fregni.pdfsiamecca mcelree 1983", "/docs/dnb/2005-fregni.pdf")
   , ("docs/iq/smpy/2oo5-wallace.pdf", "/docs/iq/smpy/2005-wallace.pdf")
   , ("docs/japanese/1997-tsuzuki-tokyoacertaistyle.pdf", "/docs/japanese/1997-tsuzuki-tokyoacertainstyle.pdf")
   , ("docs/psychology/1The emergence and evolution of school psychology literature: A scientometric analysis from 1907 through 2014998-meehl.pdf", "/docs/psychology/1998-meehl.pdf")
   , ("docs/spacedrepitition/2004-stemarie.pdf", "/docs/spacedrepetition/2004-stemarie.pdf")
   , ("docs/iq/2006-dickerson.pdf&hl=en&sa=X&scisig=AAGBfm1OJnj05UmAZMQUo227O5qStyK7PA&nossl=1&oi=scholarr&ved=2ahUKEwivl7uu8vnjAhXVGs0KHVkcDyYQgAMoAHoECAgQAg&usg=AOvVaw18rJntSRjvFL48p6KdUdUj&cshid=1565494813549", "/docs/iq/2006-dickerson.pdf")
   , ("r/DarkNetMarkets/comments/30tudk/psa_5_reddit_accounts_subpoenaed_by_ice/index.html%3Futm_name%3DDarkNetMarkets", "/docs/sr/2015-03-30-gwern-redditsubpoena.html")
   , ("Spaced-repetition scv7000ss recepie", "/Spaced-repetition")
   , ("Bitcoin-isWorse-is-Better", "/Bitcoin-is-Worse-is-Better")
   , ("DNN-archives", "/DNM-archives")
   , ("docs/catnip/1930-kuo.pdfEibl-Eibesfeldt's solitary rats study", "/docs/catnip/1930-kuo.pdf")
   , ("docs/spacedrepitition.1994-hall.pdf", "/docs/spaced-repetition/1994-hall.pdf")
   , ("Terrorism-is-not-Effective.", "/Terrorism-is-not-Effective")
   , ("Death-Note-anonymity", "/Death-Note-Anonymity")
   , ("docs/1999-bradb", "/docs/ai/1999-bradbury-matrioshkabrains.pdf")
   , ("docs/iq/1993-vernonbiologicalapproachestudyhumanintelligence.pdf", "/docs/iq/1993-vernon-biologicalapproachestudyhumanintelligence.pdf")
   , ("featured", "/index")
   , ("LSD-microdosing.html", "/LSD-microdosing")
   , ("docs/economics/2006-anonymous-currintradingponzischeme.html", "/docs/economics/2006-james315-currintradingponzischeme.html")
   , ("docs/ai/2019-07-21", "/docs/ai/2019-07-21-taotehching-all-1ksamples.txt")
   , ("ABtesting", "/AB-testing")
   , ("docs/eva/2005-sawaragi-on-the-battlefield-of-superflat-subculture-and-art-in-postwar-japan", "/docs/eva/2005-sawaragi")
   , ("mistkaes", "/Mistakes")
   , ("docs/statistics/decision/1994-benter.pdf](https://www.gwern.net/docs/statistics/decision/1994-benter.pdf)", "/docs/statistics/decision/1994-benter.pdf")
   , ("docs/statistics/decision/1994-benter.pdf](https://www.gwern.net/docs/statistics/decision/1994-benter.pdf", "/docs/statistics/decision/1994-benter.pdf")
   , ("Resilient-Haskell-software", "/Resilient-Haskell-Software")
   , ("docs/sr/2019-04-22-deepdotweb-dnmlist.htm", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("agent", "/index")
   , ("android_asset/html/article-mobile.html", "/index")
   , ("face", "/Faces")
   , ("images/genetics/chi-dna.svg", "/images/icons/chi-dna.svg")
   , ("images/erowid.svg", "/images/icons/erowid.svg")
   , ("docs/genetics/heritable/2014-deryaku.pdf", "/docs/genetics/heritable/2014-deryakulu.pdf")
   , ("language", "/Language")
   , ("docs/ai/2019-winkler.pdf.", "/docs/ai/2019-winkler.pdf")
   , ("docs/iq/2007-strenze.pdfa", "/docs/iq/2007-strenze.pdf")
   , ("docs/catnip/1962-todd.pdf [Accessed 21 Aug. 2019].", "/docs/catnip/1962-todd.pdf")
   , ("docs/sr/2013-van-hout-pdf", "/docs/sr/2013-van-hout.pdf")
   , ("docs/sunkcosts/1972-trivers.[df", "/docs/sunkcosts/1972-trivers.pdf")
   , ("Greenlannews channels ratings", "/Greenland")
   , ("modifinil", "/Modafinil")
   , ("plugins/interwiki.hs", "/static/plugins/Interwiki.hs")
   , ("site.hs", "/hakyll.hs")
   , ("Spaced repetition Vermeer, Alex. Anki Essentials v1.1: The complete guide to remembering anything with Anki . Foggy Mountain Pass. Kindle-Version.", "/Spaced-repetition")
   , ("static/plugins/interwiki.hs", "/static/plugins/Interwiki.hs")
   , ("TANKS", "/Tanks")
   , ("docs/transhumanism/1990-regis-greatmambochicken.pdf", "/docs/transhumanism/1990-regis-greatmambochickenandthetranshumancondition.pdf")
   , ("docs/anime/2014-tamerlane-animeyearbyyear-2012.html", "/docs/anime/2014-tamerlane-animeyearbyyear-2001.html")
   , ("tags/newsletter).", "/tags/newsletter")
   , (" gwern", "/index")
   , ("Death-note-anonymity I y", "/Death-Note-anonymity")
   , ("docs/cukture/2912-russell.pdf", "/docs/culture/2012-russell.pdf")
   , ("docs/sr/2019-04-23-deepdotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("Spaced-repetition.log", "/Spaced-repetition")
   , ("tags/haskell", "/tags/Haskell")
   , ("tags/newsletter.", "/tags/newsletter")
   , ("Turin?fbclid=IwAR0z4c8HyrkAfrrjPo1iPirhQMPfnwNPz702wATzD0KGv4juZx7j34pnjRw", "/Turing-complete")
   , ("docs/psychology/2017-kirschner.pdf%3Chttps:/urldefense.proofpoint.com/v2/url?u=https-3A__www.gwern.net_docs_psychology_2017-2Dkirschner.pdf&d=DwMGaQ&c=vTCSeBKl9YZZHWJzz-zQUQ&r=NksmNiFKmjbXK3ezGHAsXhxdv5libDtFX85gzp0R0pw&m=D0F0E40PvqIZzhM2Ov5JCcnJYQ_rNPX7MoYFshqzcuM&s=a_Fc_OTEo95w-GpcwvsMV45l6oXGq2LFE-Eg08Tv27w&e=", "/docs/psychology/2017-kirschner.pdf")
   , ("docs/psychology/okcupid/yourlooksandyourinbox.html](https://www.gwern.net/docs/psychology/okcupid/yourlooksandyourinbox.html?fbclid=IwAR3STIttwvWrr9HAjjWeT275ts23qkxu-WdxcAo03pMmo30NpLyM6X_qkD4", "/docs/psychology/okcupid/yourlooksandyourinbox.html")
   , ("docs/1999-bradbury-matrioshkabrains.pdf&amp", "/docs/ai/1999-bradbury-matrioshkabrains.pdf")
   , ("nootropics/index.html", "/Nootropics")
   , ("docs/psychology/1995-westby.pdf](https://www.gwern.net/docs/psychology/1995-westby.pdf", "/docs/psychology/1995-westby.pdf")
   , (".../weexperimentonhumanbeings.html", "/docs/psychology/okcupid/weexperimentonhumanbeings.html")
   , (".../okcupid/yourlooksandyourinbox.html", "/docs/psychology/okcupid/yourlooksandyourinbox.html")
   , ("docs/ps...d/yourlooksandyourinbox.html", "/docs/psychology/okcupid/yourlooksandyourinbox.html")
   , ("DNM-busts", "/DNM-arrests")
   , ("docs/smpy/1994-heller-competenceandresponsibility3rdconference.pdf", "/docs/iq/smpy/1994-heller-competenceandresponsibility3rdconference.pdf")
   , ("T3JkZXItc3", "/index")
   , ("Drug-heuristics arguements for flowers of Algernon", "/Drug-heuristics")
   , ("docs/bitcoin/pirateat40/SEC vs. pirateat40 1.pdf", "/docs/bitcoin/pirateat40/secvs.pirateat401.pdf")
   , ("docs/bitcoin/pirateat40/SEC vs. pirateat40 2.pdf", "/docs/bitcoin/pirateat40/secvs.pirateat402.pdf")
   , ("docs/statistics/decision/1994-benter.PDF", "/docs/statistics/decision/1994-benter.pdf")
   , ("Complement...keep", "/Complement")
   , ("docs/sociology/1974-martinson.pdf.", "/docs/sociology/1974-martinson.pdf")
   , ("docs/sociology/2003-murray-", "/docs/sociology/2003-murray-humanaccomplishment.pdf")
   , ("Everything - gossetstudent-1904", "/Everything#gossetstudent-1904")
   , ("index.xml", "/sitemap.xml")
   , ("tags/python", "/tags/Python")
   , ("docs/longevity/2019-fahy.pdf&ved=2ahUKEwiC0LDiqcHkAhVBYKwKHY8JBmsQFjADegQIAxAB&usg=AOvVaw0CzpLPM0KGjknvhLo5y8ih", "/docs/longevity/2019-fahy.pdf")
   , ("docs/genetics/heritable/2019-karlsson.pdf", "/docs/genetics/correlation/2019-karlsson.pdf")
   , ("docs/ai/2019-anumanchipalli.pdf原文網址：https://kknews.cc/science/pp9n2rz.html", "/docs/ai/2019-anumanchipalli.pdf")
   , ("docs/ai/2019/topol.pdf", "/docs/ai/2019-topol.pdf")
   , ("docs/ai/2019-topol.pdf [Accessed 11 Sep. 2019].", "/docs/ai/2019-topol.pdf")
   , ("docs/ai/2019-topol.pdfhttps://www.softwebsolutions.com/resources/AI-powered-virtual-assistants.html", "/docs/ai/2019-topol.pdf")
   , ("DOCS/LONGEVITY/2019-FAHY.PDF", "/docs/longevity/2019-fahy.pdf")
   , ("docs/longevity/2019-fahy.pdf&sa=U&ved=2ahUKEwiAuM6W1sTkAhVDUK0KHeDjAwoQFjAAegQIABAB&usg=AOvVaw3dI6jk97wnLvVP6qNj3_e1", "/docs/longevity/2019-fahy.pdf")
   , ("docs/longevity/2019-fahy", "/docs/longevity/2019-fahy.pdf")
   , ("docs/sociology/1979-sechrest.pdf 1965", "/docs/sociology/1979-sechrest.pdf")
   , ("newsletter/2019/00", "/newsletter/2019/01")
   , ("tags/iq", "/tags/IQ")
   , ("docs/japanese/2008-carter.pdf😀", "/docs/japanese/2008-carter.pdf")
   , ("docs/music-distraction/2011-huang.pdftversky and kahnemann framing effect", "/docs/music-distraction/2011-huang.pdf")
   , ("zeo/Potassium-morning-use", "/zeo/Potassium#morning-use")
   , (", https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme", "https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme")
   , ("docs/statistics/decision/994-benter.pdf", "/docs/statistics/decision/1994-benter.pdf")
   , ("supplements", "/Nootropics")
   , ("images/gan/thiswaifudoesnotexist-283.pngukm", "/images/gan/thiswaifudoesnotexist-283.png")
   , ("docs/japanese/2005-debary-sourcesofjapanesetradition.pdf", "/docs/japanese/2001-debary-sourcesofjapanesetradition.pdf")
   , (" docs/psychology/okcupid/whyyoushouldneverpayforonlinedating.html", "/docs/psychology/okcupid/whyyoushouldneverpayforonlinedating.html")
   , ("docs/music-distraction/2014-miller.pdf.", "/docs/music-distraction/2014-miller.pdf")
   , ("docs/iq/2018-gensowski.pdf (https://www.gwern.net/docs/iq/2018-gensowski.pdf)", "/docs/iq/2018-gensowski.pdf")
   , ("DNB-FAQта", "/DNB-FAQ")
   , ("docs/japanese/1964-debary-sourcesofjapanesetradition.pdf", "/docs/japanese/2001-debary-sourcesofjapanesetradition.pdf")
   , ("docs/psychology/2019-hsu", "/docs/psychology/2019-hsu.pdf")
   , ("docs/psychology/2019-hsu.pdf,", "/docs/psychology/2019-hsu.pdf")
   , ("LinkMetadata.hs.", "/LinkMetadata.hs")
   , ("static/font/SourceSerifPro-BASIC-Italic.ttf", "/static/font/SourceSerifPro-BASIC-RegularItalic.ttf")
   , ("static/font/SourceSansPro-BASIC-Italic.ttf", "/static/font/SourceSansPro-BASIC-RegularItalic.ttf")
   , ("Story-Of-Your-Life)", "/Story-Of-Your-Life")
   , ("docs/sr/2018-tzanetakis.pdf%20http://linkinghub.elsevier.com/retrieve/pii/S095539591830029X", "/docs/sr/2018-tzanetakis.pdf")
   , ("docs/genetics/correlation/201The%20prediction%20of%20school%20achievement%20from%20a%20behavior%20genetic%20perspective:Results%20from%20the%20German%20twin%20study%20on%20Cognitive%20Ability,%20Self-ReportedMotivation,%20and%20School%20Achievement%20(CoSMoS)-gottschling.pdf", "/docs/genetics/correlation/2012-gottschling.pdf")
   , ("docs/genetics/correlation/201The prediction of school achievement from a behavior genetic perspective:Results from the German twin study on Cognitive Ability, Self-ReportedMotivation, and School Achievement (CoSMoS)-gottschling.pdf", "/docs/genetics/correlation/2012-gottschling.pdf")
   , ("docs/psychology/1941-cleckley-maskofsanity.pdf&as_qdr=y15", "/docs/psychology/1941-cleckley-maskofsanity.pdf")
   , ("Faceshttps://www.gwern.net/Faceshttps://www.gwern.net/Faces", "/Faces")
   , ("docs/economics/1688-delavega-confusionofconfusions.Do Individual Investors Drive Post-Earnings Announcement Drift?Direct Evidence from Personal Trades.=", "/docs/economics/1688-delavega-confusionofconfusions.pdf")
   , ("Everythingslatestarcodex", "/Everything")
   , (" GPT-2.", "/GPT-2")
   , ("docs/genetics/selection/2019-hecht", "/docs/genetics/selection/2019-hecht.pdf")
   , ("docs/statistics/decision/2006-drescher-goodandreal.pdf',", "/docs/statistics/decision/2006-drescher-goodandreal.pdf")
   , ("docs/psychology/2013-hurlbert.pdf", "/docs/psychology/2013-hurlburt.pdf")
   , ("docs/genetics/heritable/1988-rowley.pdf.", "/docs/genetics/heritable/1988-rowley.pdf")
   , ("docs/spacedrepetition/1994-graesser", "/docs/spacedrepetition/1994-graesser.pdf")
   , ("docs/iq/2002-murray.pdf_", "/docs/iq/2002-murray.pdf")
   , ("docs/statistik/decision/1939-taylor.pdf", "/docs/statistics/decision/1939-taylor.pdf")
   , ("docs/iq/2015-tenijenhuis.pdf&ved=2ahUKEwjM5Jnd7PbkAhVjQUEAHaDJAP8QFjAAegQIBRAC&usg=AOvVaw1cr1IIELP10PLZh0w4EAO3", "/docs/iq/2015-tenijenhuis.pdf")
   , ("docs/psychology/2019-letexier", "/docs/psychology/2019-letexier.pdf")
   , ("docs/sr/2019-04-22-deepdotweb-dnmlist.htmlgo", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/caligirl-prfile.htm", "/docs/sr/caligirl-profile.htm")
   , ("f", "/Faces")
   , ("economics", "/docs/economics/index.html")
   , ("meletonin", "/Melatonin")
   , ("MP", "/MLP")
   , ("zeo/Vitamin-", "/zeo/Vitamin-D")
   , ("docs/genetics/heritable/1986-plomin-thestudyoftemperamen6. Why is the social-interactionist perspective attractive to many investigators of language development?t.pdf=", "/docs/genetics/heritable/1986-plomin-thestudyoftemperament.pdf")
   , ("docs/genetics/heritable/1995-serpell-thedomesticdDogs : how to choose and care for a dogog.pdf", "/docs/genetics/heritable/1995-serpell-thedomesticdog.pdf")
   , ("docs/sociology/1974-martinson.pdf (martinson)", "/docs/sociology/1974-martinson.pdf")
   , ("docs/.../1986-modgil-hanseysenckconsensusandcontroversy.pdf", "/docs/psychology/1986-modgil-hanseysenckconsensusandcontroversy.pdf")
   , ("docs/rotten.com/library/history/countries/egypt/index.html", "/docs/rotten.com/library/index.html")
   , ("docs/rotten.com/library/history/countries/Egypt/index.html", "/docs/rotten.com/library/index.html")
   , ("docs/music-distraction/1989-salame.pdf)", "/docs/music-distraction/1989-salame.pdf")
   , ("docs/music-distraction/2002-hallam.pdfYoung Adults, Music and Psychological Well-Being: Exploring the Prospects.", "/docs/music-distraction/2002-hallam.pdf")
   , ("docs/psychology/2006frattaroli.pdf", "/docs/psychology/2006-frattaroli.pdf")
   , ("docs/spacedrepet...", "/docs/spacedrepetition/index.html")
   , ("Inflation", "Inflation.hs")
   , ("mugging-dp", "/Mugging-DP")
   , ("Mugging-dp", "/Mugging-DP")
   , ("mugging-DP", "/Mugging-DP")
   , ("muggingDP", "/Mugging-DP")
   , ("muggingdp", "/Mugging-DP")
   , ("muggingd", "/Mugging-DP")
   , ("Mugging-D", "/Mugging-DP")
   , ("Mugging-", "/Mugging-DP")
   , ("Danbooru2018https://www.gwern.net/Danbooru2018", "/Danbooru2019#danbooru2018")
   , ("docs/iq/2007-strenze.pdf&ved=2ahUKEwiC0YTR_Y_lAhUWAxAIHXVrCOIQFjABegQIARAB&usg=AOvVaw1qc8H3nnM1YwkEeYDoklG1?fbclid=IwAR25MhywercEFD3l_vEphL62aFVYVyWyd4P2yHm_alo2K_vbmK86nESRTrE", "/docs/iq/2007-strenze.pdf")
   , ("docs/melatonin/2001-pacchierotti.pdf - disorders", "/docs/melatonin/2001-pacchierotti.pdf")
   , ("docs/music-distraction/2001-ransdell.pdfSalamé & Baddeley (1989). Effects of Background Music on Phonological Short-Term Memory.", "/docs/music-distraction/2001-ransdell.pdf")
   , ("docs/rotten.com/library/bio/authors/Richard_Scarry/index.html", "/docs/rotten.com/library/bio/authors/richard-scarry/index.html")
   , ("docs/sociology/2003-murray- humanaccomplishment.pdf", "/docs/sociology/2003-murray-humanaccomplishment.pdf")
   , ("docs/sociology/2003-murray-20humanaccomplishment.pdf", "/docs/sociology/2003-murray-humanaccomplishment.pdf")
   , ("docs/sr/2019-04-22-deepdo", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/2019-04-22-deepdotweb", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("newsletter/2019/9", "/newsletter/2019/09")
   , ("docs/psychology/2019orben.pdf?fbclid=IwAR2BvpVWkfbXXynNPgrxNC1dqoJqs4UeOOgiB0VHjAg8jvAz2DoXBKayRhc", "/docs/psychology/2019-orben.pdf")
   , ("docs/traffic/2007-mccovpdf", "/docs/traffic/2007-mccoy.pdf")
   , ("Faces（英文）这篇博客，TWDNE这个坑就是博主做的，其实都是预生成好了的图片并不是实时的，每次访问都是随机取一张（估计是为了速度", "/Faces")
   , ("bookbutts", "/Book-reviews")
   , ("Danbooru2918", "/Danbooru2019#danbooru2018")
   , ("docs/2002-notenki-memoirs.pdf.", "/docs/eva/2002-takeda-notenkimemoirs.pdf")
   , ("docs/anime/1967-wagatsuma.pdf0", "/docs/anime/1967-wagatsuma.pdf")
   , ("docs/cs/2001-demarco-peopleware-", "/docs/cs/2001-demarco-peopleware-whymeasureperformance.pdf")
   , ("docs/dnb/2000-butzlaff.pdfCampbell, P. S. (1989). Orality, literacy and music's creative potential: A comparative approach. Bulletin of the Council for Research in Music Education, (101), 30-40.", "/docs/dnb/2000-butzlaff.pdf")
   , ("docs/genetics/2016-plomin.pdf ,", "/docs/genetics/2016-plomin.pdf")
   , ("docs/iq/2007-zagorsky.pdf https://hypertextbook.com/facts/2006/bodyproportions.shtml", "/docs/iq/2007-zagorsky.pdf")
   , ("docs/iq/2007-zagorsky.pdf https://hypertextbook.com/facts/2006/bodyproportions.shtml https://hypertextbook.com/facts/2006/bodyproportions.shtml", "/docs/iq/2007-zagorsky.pdf")
   , ("docs/music-distraction/2011-huang.pdf.", "/docs/music-distraction/2011-huang.pdf")
   , ("docs/rotten.com/library/index.com", "/docs/rotten.com/library/index.html")
   , ("docs/statistics/decision/brecher-1980.pdf", "/docs/statistics/decision/1980-brecher.pdf")
   , ("spaced-repatition", "/Spaced-repetition")
   , ("TWDNE2", "/TWDEN")
   , ("wikipedia", "/tags/Wikipedia")
   , ("docs/genetics/heritable/1996-heston.pdf", "/docs/genetics/heritable/1966-heston.pdf")
   , ("Modafinil.code", "/Modafinil.page")
   , ("Modafinil.source", "/Modafinil.page")
   , (" faces", "/Faces")
   , ("docs/conscientiousness/2003-lounsbury.pdfBa, H., Tally, W., & Tsikalas, K. (2002). Investigating children’s emerging digital literacies. The Journal of Technology, Learning, and Assessment, 1(4), 5-48.", "/docs/conscientiousness/2003-lounsbury.pdf")
   , ("docs/psychology/1952-asch.pdf [24.04.2018]", "/docs/psychology/1952-asch.pdf")
   , ("docs/rotten.com/library/conspiracy/American_Concentation_Camps/index.html", "/docs/rotten.com/library/conspiracy/american-concentration-camps/index.html")
   , ("docs/rotten.com/library/conspiracy/american-concentation-camps/index.html", "/docs/rotten.com/library/conspiracy/american-concentration-camps/index.html")
   , ("docs/sociology/1983-dimmagio.pdf", "/docs/sociology/1983-dimaggio.pdf")
   , ("docs/spacedrepetition/1939-spitzer.pdf.", "/docs/spacedrepetition/1939-spitzer.pdf")
   , ("docs/spacedrepetition/1987-adams.p", "/docs/spacedrepetition/1987-adams.pdf")
   , ("DOcs/sr/2019-04-22-deepdotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/2019-04-22french dark netdeepdotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/statistics/deceision/1994.benter.pdf", "/docs/statistics/decision/1994-benter.pdf")
   , ("nudes", "/TWDNE")
   , ("rss2.xml", "https://www.reddit.com/r/gwern/search.rss?q=flair:'Gwern'&sort=new&restrict_sr=on")
   , ("atom.xml", "https://www.reddit.com/r/gwern/search.rss?q=flair:'Gwern'&sort=new&restrict_sr=on")
   , ("feeds", "https://www.reddit.com/r/gwern/search.rss?q=flair:'Gwern'&sort=new&restrict_sr=on")
   , ("feed.xml", "https://www.reddit.com/r/gwern/search.rss?q=flair:'Gwern'&sort=new&restrict_sr=on")
   , ("sr/index.html", "/docs/sr/index.html")
   , ("docs/ai/2013-clark.pdf", "http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.259.7600&rep=rep1&type=pdf")
   , ("docs/catnip/2000-turner-thedomesticcat.pdf", "/static/404.html")
   , ("docs/cs/2004-hughes.pdf", "https://pdfs.semanticscholar.org/1511/691d858038f5078a647c21e2ac62b790d31b.pdf")
   , ("docs/economics/1973-ellman-planningproblemsintheussr.pdf", "/static/404.html")
   , ("docs/economics/2003-gaspard.pdf", "/static/404.html")
   , ("docs/genetics/correlation/1993-kendler.pdf", "https://www.researchgate.net/profile/Michael_Neale/publication/231747988_Major_Depression_and_Phobias_The_Genetic_and_Environmental_Sources_of_Comorbidity/links/53d66c990cf228d363ea5613.pdf")
   , ("docs/genetics/correlation/2002-nadder.pdf", "/static/404.html")
   , ("docs/genetics/correlation/2003-kendler.pdf", "https://pdfs.semanticscholar.org/07bd/9116f5f9f00626fa7b8dab56d139d106a56f.pdf")
   , ("docs/genetics/correlation/2017-aas.pdf", "https://www.duo.uio.no/bitstream/handle/10852/64121/preprint_cannabis.pdf?sequence=4")
   , ("docs/genetics/correlation/2017-docherty.pdf", "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5971142/")
   , ("docs/genetics/correlation/2018-chen.pdf", "/static/404.html")
   , ("docs/genetics/correlation/2018-mallard.pdf", "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6711829/")
   , ("docs/genetics/heritable/1995-serpell-thedomesticdog.pdf", "/static/404.html")
   , ("docs/genetics/heritable/2006-kendler.pdf", "/static/404.html")
   , ("docs/genetics/heritable/2012-burt.pdf", "https://www.researchgate.net/profile/Wim_Crusio/publication/232698813_Heritability_estimates_in_behavior_genetics_Wasn't_that_station_passed_long_ago/links/5603ff6908aefaf89ef9d43f.pdf")
   , ("docs/genetics/heritable/2017-lu.pdf", "/static/404.html")
   , ("docs/genetics/heritable/2018-davis.pdf", "https://keppel.qimr.edu.au/contents/p/staff/DavisCN_2018PsychMed_EPUB.pdf")
   , ("docs/genetics/selection/1986-russell-likeengendringlike.pdf", "/static/404.html")
   , ("docs/genetics/selection/2016-weight.pdf", "https://www.cambridge.org/core/services/aop-cambridge-core/content/view/A8887CDB53100F6A4D3AD0E5AECA6440/S002193201600002Xa.pdf/some_uses_of_models_of_quantitative_genetic_selection_in_social_science.pdf")
   , ("docs/iq/1931-lawrence-investigationrelationbetweenintelligenceinheritance.pdf", "https://wellcomelibrary.org/item/b18032217")
   , ("docs/iq/1993-carroll-humancognitiveabilitiessurveyfactoranalyticstudies.pdf", "/static/404.html")
   , ("docs/iq/1996-sternberg-intelligenceheredityandenvironment.pdf", "/static/404.html")
   , ("docs/iq/2015-carl.pdf", "https://pdfs.semanticscholar.org/deb6/b2558cb9bc5ba166390ca153f95634403659.pdf")
   , ("docs/iq/2019-tenijenhuis.pdf", "/static/404.html")
   , ("docs/japanese/1959-saikaku-thejapanesefamilystorehouse.pdf", "/static/404.html")
   , ("docs/math/1986-littlewood-littlewoodsmiscellany.pdf", "https://archive.org/details/mathematiciansmi033496mbp/page/n1")
   , ("docs/math/1988-korner-fourieranalysis.pdf", "/static/404.html")
   , ("docs/statistics/1963-aitchison-thelognormaldistribution.pdf", "/static/404.html")
   , ("images/icons/chi-dna.svg", "/static/img/icons/chi-dna.svg")
   , ("images/icons/deepmind.svg", "/static/img/icons/deepmind.svg")
   , ("images/icons/erowid.svg", "/static/img/icons/erowid.svg")
   , ("images/icons/google-scholar.svg", "/static/img/icons/google-scholar.svg")
   , ("images/icons/internetarchive.svg", "/static/img/icons/internetarchive.svg")
   , ("images/icons/miri.svg", "/static/img/icons/miri.svg")
   , ("images/icons/newyorktimes.svg", "/static/img/icons/newyorktimes.svg")
   , ("images/icons/nlm-ncbi.svg", "/static/img/icons/nlm-ncbi.svg")
   , ("images/icons/openai.svg", "/static/img/icons/openai.svg")
   , ("images/icons/theguardian.svg", "/static/img/icons/theguardian.svg")
   , ("images/icons/thenewyorker.svg", "/static/img/icons/thenewyorker.svg")
   , ("images/icons/washingtonpost.svg", "/static/img/icons/washingtonpost.svg")
   , ("Arafinil", "/Modafinil")
   , ("Culture-is-not-about-Esthetics.md", "Culture-is-not-about-Esthetics.page")
   , ("Culture-is-not-about-Esthetics.source", "Culture-is-not-about-Esthetics.page")
   , ("docs/dnb/2010-alloway.pdfInvestigating the predictive roles of working memory and IQ in academic attainment", "/docs/dnb/2010-alloway.pdf")
   , ("docs/psychology/2018-williams-2.pdf&ved=2ahUKEwi-", "/docs/psychology/2018-williams-2.pdf")
   , ("docs/rotten.com/library/bio/royalty/america/emperor-no", "//docs/rotten.com/library/bio/royalty/america/emperor-norton/index.html")
   , ("docs/sr/2019-04-22-deepdotweb-dnmlist.html.com", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/statistics/order/beanmachine-multistage/index.%E2%80%8Bhtml", "/docs/statistics/order/beanmachine-multistage/index.html")
   , ("tool-ai", "/Tool-AI")
   , ("dnbfaq", "/DNB-FAQ")
   , ("docs/sr/2019-04-22-deepdotweb-dnmlist,html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("tag/newsletter", "/tags/newsletter")
   , ("docs/borges/1951-borges-kafkaand", "/docs/borges/1951-borges-kafkaandhisprecursors.pdf")
   , ("DNM-arrests since we should typically good, better than competitors", "/DNM-arrests")
   , ("docs/genetics/correlation/1978-nance-twinresearchpartapsychologymethodology.pdf", "/docs/genetics/correlation/1978-nance-twinresearchparta-psychologymethodology.pdf")
   , ("Black-market arrest", "/DNM-arrests")
   , ("Danbooru2018%20%E5%8E%9F%E6%96%87%E7%B6%B2%E5%9D%80%EF%BC%9Ahttps://kknews.cc/comic/3a3ap4a.html"," /Danbooru2018")
   , ("D‌N‌M‌‌-survival", "/DNM-survival")
   , ("docs/psychology/1941-cleckley-maskofsanity.pdf,", "/docs/psychology/1941-cleckley-maskofsanity.pdf")
   , ("docs/sociology/1974-Martinson.pdf", "/docs/sociology/1974-martinson.pdf")
   , ("docs/genetics/heritable/2019-kandler-2.pdfA", "/docs/genetics/heritable/2019-kandler-2.pdf")
   , ("docs/sr/2019-04-22-deepotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/music-distraction/2014-miller.pd", "/docs/music-distraction/2014-miller.pdf")
   , ("archiving-urls", "/Archiving-URLs")
   , ("DNB-faq", "/DNB-FAQ")
   , ("docs/music-distraction/1989/-salme.pdf", "/docs/music-distraction/1989-salme.pdf")
   , ("docs/music-distraction/2011-huag.pdf", "/docs/music-distraction/2011-huang.pdf")
   , ("docs/spacedrepetition/1994-hall.pdf).", "/docs/spacedrepetition/1994-hall.pdf")
   , ("docs/sr/2019-04-22-deepdotwbp-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/2019-04-22-deepdotwep-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/2019-04-22-deepotwep-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/sr/2019-04-22-darknet-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("docs/genetics/heritable/1965-scott-geneticsandthesocialbehaviourofthedog.pdf", "/docs/genetics/heritable/1965-scott-geneticsandthesocialbehaviorofthedog.pdf")
   , ("docs/genetics/heritable/1965-scott geneticsandthesocialbehaviorofthedog.pdf", "/docs/genetics/heritable/1965-scott-geneticsandthesocialbehaviorofthedog.pdf")
   , ("docs/ai/2019-bashivan.pdf et un truc qui nous interesse pour notre modele a plus laurent", "/docs/ai/2019-bashivan.pdf")
   , ("docs/culture/2010dobelli.pdf", "/docs/culture/2010-dobelli.pdf")
   , ("docs/culture/2010-dobelli.pdf&campaign_id=4633", "/docs/culture/2010-dobelli.pdf")
   , ("About.pag", "/About.page")
   , ("docs/genetics/editing/2017-tang", "/docs/genetics/editing/2017-tang.pdf")
   , ("docs/music-distraction/1989-salame.pdf https://sites.psu.edu/siowfa15/2015/12/03/background-music-and-its-affects-on-studying/index.html", "/docs/music-distraction/1989-salame.pdf")
   , ("docs/philo/1927-ramsey.pdfnet", "/docs/philo/1927-ramsey.pdf")
   , ("embryo-editing", "/Embryo-editing")
   , ("newsletter/2019/19", "/newsletter/2019/09")
   , ("tags/r", "/tags/R")
   , ("tags/smpy", "/tags/SMPY")
   , ("docs/history/1969-boorman-theprotractedgame.pdf`qtyuiop[]/8/]=[-0p98y67t5r4wqQSWDEFRGTHY JUKILO", "/docs/history/1969-boorman-theprotractedgame.pdf")
   , ("docs/xrisks/2012-schneier-liarsandoutliers-", "/docs/xrisks/2012-schneier-liarsandoutliers-ch13.pdf")
   , ("newsletter/2019/090", "/newsletter/2019/09")
   , ("docs/ai/2018-09-22-progan-holofaces-topdecile.tar.xz", "/docs/ai/anime/2018-09-22-progan-holofaces-topdecile.tar.xz")
   , ("docs/ai/2019-02-06-progan-danbooru2017-faces-randomsamples.tar", "/docs/ai/anime/2019-02-06-progan-danbooru2017-faces-randomsamples.tar")
   , ("docs/ai/2019-02-10-stylegan-holo-handselectedsamples.zip", "/docs/ai/anime/2019-02-10-stylegan-holo-handselectedsamples.zip")
   , ("docs/ai/2019-02-11-stylegan-asuka-handselectedsamples.zip", "/docs/ai/anime/2019-02-11-stylegan-asuka-handselectedsamples.zip")
   , ("docs/ai/2019-02-28-thiswaifudoesnotexist-textsnippets.tar.xz", "/docs/ai/anime/2019-02-28-thiswaifudoesnotexist-textsnippets.tar.xz")
   , ("docs/ai/2019-10-21-gwern-gpt2-folkrnn-samples.ogg", "/docs/ai/music/2019-10-21-gwern-gpt2-folkrnn-samples.ogg")
   , ("docs/ai/2019-10-22-gwern-gpt2-irish-paddywhack.ogg", "/docs/ai/muusic/2019-10-22-gwern-gpt2-irish-paddywhack.ogg")
   , ("docs/ai/2019-10-22-gwern-gpt2-irish-thebankofturf.ogg", "/docs/ai/music/2019-10-22-gwern-gpt2-irish-thebankofturf.ogg")
   , ("docs/ai/2019-10-23-gwern-gpt2-folkrnn-irishmusic-samples.txt", "/docs/ai/music/2019-10-23-gwern-gpt2-folkrnn-irishmusic-samples.txt")
   , ("docs/ai/2019-10-23-gwern-gpt2-irish-hickeystune.ogg", "/docs/ai/music/2019-10-23-gwern-gpt2-irish-hickeystune.ogg")
   , ("docs/ai/2019-10-29-theloonandhisquine.ogg", "/docs/ai/music/2019-10-29-theloonandhisquine.ogg")
   , ("docs/ai/2019-10-30-theatlanticroar.ogg", "/docs/ai/music/2019-10-30-theatlanticroar.ogg")
   , ("docs/ai/2019-10-30-thelonelyfireside.ogg", "/docs/ai/music/2019-10-30-thelonelyfireside.ogg")
   , ("docs/ai/2019-10-31-themarine.ogg", "/docs/ai/music/2019-10-31-themarine.ogg")
   , ("docs/ai/2019-10-31-whiskeybeforebreakfast.ogg", "/docs/ai/music/2019-10-31-whiskeybeforebreakfast.ogg")
   , ("docs/ai/2019-11-01-theflogging.ogg", "/docs/ai/music/2019-11-01-theflogging.ogg")
   , ("docs/ai/2019-11-03-banksoftheallan.ogg", "/docs/ai/music/2019-11-03-banksoftheallan.ogg")
   , ("docs/ai/2019-11-04-ashortjourney.ogg", "/docs/ai/music/2019-11-04-ashortjourney.ogg")
   , ("docs/ai/2019-11-08-gpt2-irish-spaceless-100medley.ogg", "/docs/ai/music/2019-11-08-gpt2-irish-spaceless-100medley.ogg")
   , ("docs/ai/2019-11-08-gpt2-nospaces-samples.txt", "/docs/ai/music/2019-11-08-gpt2-nospaces-samples.txt")
   , ("docs/ai/2019-11-09-gpt2-irish-spaceless-50medley-topp0.99.ogg", "/docs/ai/music/2019-11-09-gpt2-irish-spaceless-50medley-topp0.99.ogg")
   , ("docs/ai/2019-11-09-gpt2-irish-spaceless-50medley.ogg", "/docs/ai/music/2019-11-09-gpt2-irish-spaceless-50medley.ogg")
   , ("docs/ai/2019-11-09-gpt2-nospaces-samples-top_p0.99.txt", "/docs/ai/music/2019-11-09-gpt2-nospaces-samples-top_p0.99.txt")
   , ("docs/ai/2019-11-09-gpt2-nospaces-samples.txt", "/docs/ai/music/2019-11-09-gpt2-nospaces-samples.txt")
   , ("docs/ai/2019-11-09-ynbollanbane.txt", "/docs/ai/music/2019-11-09-ynbollanbane.txt")
   , ("docs/ai/2019-11-10-gpt2-irish-spaceless-50variantsonynbollanbane.ogg", "/docs/ai/music/2019-11-10-gpt2-irish-spaceless-50variantsonynbollanbane.ogg")
   , ("docs/ai/2016-03-27-rnn-metadata-samples-all.txt", "/docs/ai/poetry/2016-03-27-rnn-metadata-samples-all.txt")
   , ("docs/ai/2016-03-27-rnn-metadata-samples.txt", "/docs/ai/poetry/2016-03-27-rnn-metadata-samples.txt")
   , ("docs/ai/2019-03-06-gpt2-poetry-1000samples.txt", "/docs/ai/poetry/2019-03-06-gpt2-poetry-1000samples.txt")
   , ("docs/ai/2019-03-06-gpt2-poetry-prefix-1000samples.txt", "/docs/ai/poetry/2019-03-06-gpt2-poetry-prefix-1000samples.txt")
   , ("docs/ai/2019-03-16-gpt2-poetry-prefix-jabberwocky-100samples.txt", "/docs/ai/poetry/2019-03-16-gpt2-poetry-prefix-jabberwocky-100samples.txt")
   , ("docs/ai/2019-05-13-gpt2-poetry-345m-5000samples.txt", "/docs/ai/poetry/2019-05-13-gpt2-poetry-345m-5000samples.txt")
   , ("docs/ai/2019-05-24-gpt2-poetry-yeatssecondcoming-500completions.txt", "/docs/ai/poetry/2019-05-24-gpt2-poetry-yeatssecondcoming-500completions.txt")
   , ("docs/ai/2019-07-19-taotehching-ch1-1ksamples.txt", "/docs/ai/poetry/2019-07-19-taotehching-ch1-1ksamples.txt")
   , ("docs/ai/2019-07-21-taotehching-all-1ksamples.txt", "/docs/ai/poetry/2019-07-21-taotehching-all-1ksamples.txt")
   , ("docs/ai/2019-10-17-117m-poetry-cleanprojectgutenberg-samples.txt", "/docs/ai/poetry/2019-10-17-117m-poetry-cleanprojectgutenberg-samples.txt")
   , ("docs/ai/2019-10-19-117m-poetryfoundation-samples.txt", "/docs/ai/poetry/2019-10-19-117m-poetryfoundation-samples.txt")
   , ("docs/2013-ioannidis.pdf", "/docs/statistics/bias/2013-ioannidis.pdf")
   , ("the-melancholy-of-subulture-society", "/The-Melancholy-of-Subculture-Society")
   , ("docs/fiction/1980-omni-juNE.pdf", "/docs/fiction/1980-omni-june.pdf")
   , ("docs/melatonin/2005-brzezinski.pdf.", "/docs/melatonin/2005-brzezinski.pdf")
   , ("Black-market arrests ~311 arrests", "/DNM-arrests")
   , ("Black-market arrests ~311 arrests or busts related to the DNMs. Suggestions welcome.", "/DNM-arrests")
   , ("black-market%archives", "/DNM-archives")
   , ("docs/psychology/2019-shewach.pdf…", "/docs/psychology/2019-shewach.pdf")
   , ("docs/spacedrepetition/1981-bloom.pdfgoogle", "/docs/spacedrepetition/1981-bloom.pdf")
   , ("facea", "/Faces")
   , ("res", "/Research-criticism")
   , ("srs", "/Spaced-repetition")
   , ("docs/rotten.com/library/imagery/subliminal/neo-geo/index.html", "/docs/rotten.com/library/imagery/subliminal/advertising/neo-geo/index.html")
   , ("Greenland.", "/Greenland")
   , ("static/metadata/custom.hs", "/static/metadata/custom.yaml")
   , ("docs/statistics/2015-franco.pdf%20http://journals.sagepub.com/doi/10.1177/1948550615598377", "/docs/statistics/2015-franco.pdf")
   , ("Resorter](Resorter)", "/Resorter")
   , ("docs/culture/2018-micola", "/docs/culture/2018-micola.pdf")
   , ("Notex", "/Notes")
   , ("docs/ai/2019-liang.ppt", "/docs/ai/2019-liang.pdf")
   , ("docs/sociology/1980-patton-qualitativeevaluationmethods.pdf.", "/docs/sociology/1980-patton-qualitativeevaluationmethods.pdf")
   , ("…/psyc…/1941-cleckley-maskofsanity.pdf", "/docs/psychology/1941-cleckley-maskofsanity.pdf")
   , ("psyc/1941-cleckley-maskofsanity.pdf", "/docs/psychology/1941-cleckley-maskofsanity.pdf")
   , ("Danbooru2018 http://317lab.sjtu.edu.cn/publications.html", "/Danbooru2019#danbooru2018")
   , ("Danbooru2018http://317lab.sjtu.edu.cn/publications.html", "/Danbooru2019#danbooru2018")
   , ("docs/iq/2016-carl.pdf]", "/docs/iq/2016-carl.pdf")
   , ("docs/psychology/1952-asch.pdfGroups, leadership and men", "/docs/psychology/1952-asch.pdf")
   , ("docs/sociology/2018-pianta", "/docs/sociology/2018-pianta.pdf")
   , ("docs/statistics/decision/1994-benter.pd", "/docs/statistics/decision/1994-benter.pdf")
   , ("lsd", "/LSD-microdosing")
   , ("docs/history/1978-ladurie-montaillouthepromisedlandoferror.pdf", "/docs/history/1978-ladurie-montaillouthepromisedlandoferror-chapter2domus.pdf")
   , ("docs/history/1978-ladurie-montaillouthepromisedlandoferror", "/docs/history/1978-ladurie-montaillouthepromisedlandoferror-chapter2domus.pdf")
   , ("Story-Of-Your_Life", "/Story-Of-Your-Life")
   , ("docs/sociology/1980-patton-qualitative evaluationmethods.pdf", "/docs/sociology/1980-patton-qualitativeevaluationmethods.pdf")
   , ("docs/algernon/1964-simpson.pdfhttps://www.bartleby.com/173/31.html", "/docs/algernon/1964-simpson.pdf")
   , ("bitcoin", "/Bitcoin-is-Worse-is-Better")
   , ("docs/dnb/2010-alloway.pd", "/docs/dnb/2010-alloway.pdf")
   , ("docs/economics/2017-schmidt.pdf thesis", "/docs/economics/2017-schmidt.pdf")
   , ("docs/genetics/editing/2019-fredens.pdf.?fbclid=IwAR3XI_d0UbMJoIWDJFM3g0iXdttJVgtnNs_zqcnHloO23Dm1EgHZEUHnWMU", "/docs/genetics/editing/2019-fredens.pdf")
   , ("docs/iq/2018-hegelund.pdf.", "/docs/iq/2018-hegelund.pdf")
   , ("docs/music-distraction/2009-katner.pdf", "/docs/music-distraction/2009-kantner.pdf")
   , ("docs/psychology/2019-orben.pdf.", "/docs/psychology/2019-orben.pdf")
   , ("timestamping", "/Timestamping")
   , ("docs/iq/smpy/stique.pdf", "/docs/iq/smpy/1980-fox-womenandthemathematicalmystique.pdf")
   , ("docs/genetics/heritable/1973-dobzhansky-geneticdiversityandhumanequality.pdf.", "/docs/genetics/heritable/1973-dobzhansky-geneticdiversityandhumanequality.pdf")
   , ("docs/history/1963-deroover-theriseanddeclineofmedicibank.pdf", "/docs/history/1963-deroover-theriseanddeclineofthemedicibank.pdf")
   , ("Spaced٪20repetition", "/Spaced%20repetition")
   , ("red", "/Red")
   , ("Rubrication", "/Red")
   , ("rubrication", "/Red")
   , ("docs/statistics/1990-tufte-envisioninginformation-ch5-bryneseuclid.pdf", "/docs/statistics/1990-tufte-envisioninginformation-ch5-byrneseuclid.pdf")
   , ("docs/psychology/1993-brand-painthegiftnobodywants.PDF", "/docs/psychology/1993-brand-painthegiftnobodywants.pdf")
   , ("docs/psychology/2019-vanhiel.pdf&ved=2ahUKEwi627XX0IbmAhV3H7kGHVfBAjIQFjAAegQIAhAB&usg=AOvVaw2d-NFKD7mG8MBWZWnk2an6", "/docs/psychology/2019-vanhiel.pdf")
   , ("doc[...]ctsthemessagesyouget.html", "/docs/psychology/okcupid/howyourraceaffectsthemessagesyouget.html")
   , ("docs/music-distraction/2019-gonzalez.pdf (", "/docs/music-distraction/2019-gonzalez.pdf")
   , ("docs/sociology/1962-calhoun.pdf.", "/docs/sociology/1962-calhoun.pdf")
   , ("images/rl/2017-12-24-alphagozero-meme-addmorelayers.jpg", "/images/rl/2017-12-24-meme-nnlayers-alphagozero.jpg")
   , ("Complement Found", "/Complement")
   , ("Complement Found it via http://softwareleadweekly.com/index.html", "/Complement")
   , ("Complement%20Found%20it%20via%20http://softwareleadweekly.com/index.html", "/Complement")
   , ("Complement__", "/Complement")
   , ("Danbooru2018）", "/Danbooru2019#danbooru2018")
   , ("images/gan/2019-02-11-stylegan-danbooru2017faces-interpolation.mp4&loop=1", "/images/gan/2019-02-11-stylegan-danbooru2017faces-interpolation.mp4")
   , ("complement&title=Laws+of+Tech:+Commoditize+Your+Complement", "/Complement")
   , ("docs/borges/1936-borges-thetranslatorsofthethousandandonenights", "/docs/borges/1936-borges-thetranslatorsofthethousandandonenights.pdf")
   , ("docs/genetics/editing/2019-anzalone.pd", "/docs/genetics/editing/2019-anzalone.pdf")
   , ("docs/iq/2015-roth.pdf+", "/docs/iq/2015-roth.pdf")
   , ("docs/statistics/1957-feller-anintroductiontoprobabilitytheoryanditsapplications2.pdf", "/docs/statistics/1957-feller-anintroductiontoprobabilitytheoryanditsapplications.pdf")
   , ("zeo/CO2. Accessed 7 Oct. 2019.", "/zeo/CO2")
   , ("newsletter/YEAR/13", "/tags/newsletter")
   , ("docs/spacedrepetition/2001-maquet.pdfÂ", "/docs/spacedrepetition/2001-maquet.pdf")
   , ("Spaced-repetition,Spaced Repetition - Gwern.net,,Unread,1550106686", "/Spaced-repetition")
   , ("docs/philo/1973-kubose-zenkoans.pdfhttp://www.ashidakim.com/zenkoans/zenindex.html", "/docs/philo/1973-kubose-zenkoans.pdf")
   , ("docs/spacedrepitition/1939-spitzer.pdf", "/docs/spacedrepetition/1939-spitzer.pdf")
   , ("docs/philo/1973-kubose-zenkoans.pdfhttp://www.ashidakim.com/zenkoans/index.html", "/docs/philo/1973-kubose-zenkoans.pdf")
   , ("GPT-2)", "/GPT-2")
   , ("newsletter/2012/13", "/tags/newsletter")
   , ("newsletter/2013/13", "/tags/newsletter")
   , ("newsletter/YEAR/11", "/tags/newsletter")
   , ("newsletter/YEAR/14", "/tags/newsletter")
   , ("Modafinil mail", "/Modafinil")
   , ("docs/conscienctiuosness/2019-wilmot.pdf", "/docs/conscientiousness/2019-wilmot.pdf")
   , ("docs/anime/1995-newitz.pdf.", "/docs/anime/1995-newitz.pdf")
   , ("hydrocephalus", "/Hydrocephalus")
   , ("hydrocephaly", "/Hydrocephalus")
   , ("Hydrocephaly", "/Hydrocephalus")
   , ("hemispherectomy", "/Hydrocephalus")
   , ("Hemispherectomy", "/Hydrocephalus")
   , ("improvements", "/Improvements")
   , ("improvement", "/Improvements")
   , ("Improvement", "/Improvements")
   , ("Improvment", "/Improvements")
   , ("Improvments", "/Improvements")
   , ("Ordinary", "/Improvements")
   , ("ordinary", "/Improvements")
   , ("ordinary-life-improvements", "/Improvements")
   , ("Ordinary-life-improvements", "/Improvements")
   , ("Ordinary-Life-improvements", "/Improvements")
   , ("Ordinary-Life-Improvements", "/Improvements")
   , ("Ordinary-life-Improvements", "/Improvements")
   , ("docs/iq/2017-jerrim.pdf.", "/docs/iq/2017-jerrim.pdf")
   , ("docs/music-distraction/2011-", "/docs/music-distraction/index.html")
   , ("anime", "/tags/anime")
   , ("docs/borges/1951-borges-theargentinewriterandtradition", "/docs/borges/1951-borges-theargentinewriterandtradition.pdf")
   , ("docs/iq/2017-jerrim", "docs/iq/2017-jerrim.pdf")
   , ("docs/music-distraction/2005-lesiuk.pdf ‘", "/docs/music-distraction/2005-lesiuk.pdf")
   , ("docs/psychology/1941-cleckley-maskofsanity.pdf.", "/docs/psychology/1941-cleckley-maskofsanity.pdf")
   , ("docs/sr/2019-04-22-deepdotweb-dnmlist.htmlx", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
   , ("replication", "/Replication")
   , ("replication-crisis", "/Replication")
   , ("Replication-crisis", "/Replication")
   , ("Replication-Crisis", "/Replication")
   , ("replication-Crisis", "/Replication")
   , ("Reproducibility-Crisis", "/Replication")
   , ("Reproducibility-crisis", "/Replication")
   , ("reproducibility-Crisis", "/Replication")
   , ("reproducibility-crisis", "/Replication")
   , ("docs/dnb/2010-colom.pdfdoi: 10.1080/10627197.2015.997614", "/docs/dnb/2010-colom.pdf")
   , ("docs/psychology/2014-matter-storr-themanwhodestroyedamericasego.html", "/docs/sociology/2014-02-25-matter-themanwhodestroyedamericasego.html")
   , ("docs/music-distraction/1989-salame.pdf.%20Accessed%201%20Oct.%202019.", "/docs/music-distraction/1989-salame.pdf.%20Accessed%201%20Oct.%202019.")
   , ("%22https://arxiv.org/abs/1909.05858/%22", "https://arxiv.org/abs/1909.05858")
   , ("A", "/About")
   , ("Abou", "/About")
   , ("About.source", "/About.page")
   , ("docs/culture/2006-slater.pdf - Television Dramas and Support for Controversial Public Policies: Effects and Mechanisms P236", "/docs/culture/2006-slater.pdf")
   , ("docs/ifrench school ask for iq testq/2019-platt.pdf", "/docs/iq/2019-platt.pdf")
   , ("docs/music-distraction/2012-doyle.pdf.", "/docs/music-distraction/2012-doyle.pdf")
   , ("docs/bitcoin/pirateat40/index.html", "https://www.google.com/search?num=100&q=site%3Awww%2Egwern%2Enet%2Fdocs/bitcoin/pirateat40/")
   , ("goodreads", "/GoodReads")
   , ("goodReads", "/GoodReads")
   , ("Goodreads", "/GoodReads")
   , ("GOODREADS", "/GoodReads")
   , ("Abandon", "/GoodReads")
   , ("Abandoned", "/GoodReads")
   , ("abandon", "/GoodReads")
   , ("abandoned", "/GoodReads")
   , ("GR", "/GoodReads")
   , ("gr", "/GoodReads")
   , ("inflation.hs", "/Inflation.hs")
   , ("src/inflation.hs", "/Inflation.hs")
   , ("linkMetadata.hs", "/LinkMetadata.hs")
   , ("docs/genetics/heritable/1995-serpell-thedomesticdog", "/docs/genetics/heritable/1995-serpell-thedomesticdog.pdf")
   , ("docs/iq/2018-warne-2.pdfg", "/docs/iq/2018-warne-2.pdf")
   , ("docs/sociology/2987-murray-humanaccomplishment.pdf", "/docs/sociology/2003-murray-humanaccomplishment.pdf")
   , ("docs/sociology/203-murray-humanaccomplishment", "/docs/sociology/2003-murray-humanaccomplishment.pdf")
   , ("GPT-2-Music", "/GPT-2-music")
   , ("gpt-2-music", "/GPT-2-music")
   , ("GPT-music", "/GPT-2-music")
   , ("gpt-music", "/GPT-2-music")
   , ("GPT2-music", "/GPT-2-music")
   , ("GPT2music", "/GPT-2-music")
   , ("gpt2music", "/GPT-2-music")
   , ("docs/biology/2003-cole.pdf.", "/docs/biology/2003-cole.pdf")
   , ("Piracetam", "/Nootropics#piracetam")
  , ("docs/history/1969-schirra-apollo11flighttothemoon.ogg", "/docs/history/1969-schirra-apollo11flighttothemoon.mp3")
  , ("docs/ai/music/2019-11-10-gpt2-irish-spaceless-50variantsonynbollanbane.ogg", "/docs/ai/music/2019-11-10-gpt2-irish-spaceless-50variantsonynbollanbane.mp3")
  , ("docs/ai/music/2019-10-30-theatlanticroar.ogg", "/docs/ai/music/2019-10-30-theatlanticroar.mp3")
  , ("docs/ai/music/2019-10-29-theloonandhisquine.ogg", "/docs/ai/music/2019-10-29-theloonandhisquine.mp3")
  , ("docs/ai/music/2019-10-31-whiskeybeforebreakfast.ogg", "/docs/ai/music/2019-10-31-whiskeybeforebreakfast.mp3")
  , ("docs/ai/music/2019-11-14-gwern-gpt2-127512.ogg", "/docs/ai/music/2019-11-14-gwern-gpt2-127512.mp3")
  , ("docs/ai/music/2019-11-08-gpt2-irish-spaceless-100medley.ogg", "/docs/ai/music/2019-11-08-gpt2-irish-spaceless-100medley.mp3")
  , ("docs/ai/music/2019-11-03-banksoftheallan.ogg", "/docs/ai/music/2019-11-03-banksoftheallan.mp3")
  , ("docs/ai/music/2019-11-09-gpt2-irish-spaceless-50medley-topp0.99.ogg", "/docs/ai/music/2019-11-09-gpt2-irish-spaceless-50medley-topp0.99.mp3")
  , ("docs/ai/music/2019-10-21-gwern-gpt2-folkrnn-samples.ogg", "/docs/ai/music/2019-10-21-gwern-gpt2-folkrnn-samples.mp3")
  , ("docs/ai/music/2019-11-09-gpt2-irish-spaceless-50medley.ogg", "/docs/ai/music/2019-11-09-gpt2-irish-spaceless-50medley.mp3")
  , ("docs/ai/music/2019-12-04-gpt2-combinedabc-invereshieshouse.ogg", "/docs/ai/music/2019-12-04-gpt2-combinedabc-invereshieshouse.mp3")
  , ("docs/ai/music/2019-10-22-gwern-gpt2-irish-thebankofturf.ogg", "/docs/ai/music/2019-10-22-gwern-gpt2-irish-thebankofturf.mp3")
  , ("docs/ai/music/2019-10-31-themarine.ogg", "/docs/ai/music/2019-10-31-themarine.mp3")
  , ("docs/ai/music/2019-11-01-theflogging.ogg", "/docs/ai/music/2019-11-01-theflogging.mp3")
  , ("docs/ai/music/2019-11-04-ashortjourney.ogg", "/docs/ai/music/2019-11-04-ashortjourney.mp3")
  , ("docs/ai/music/2019-10-22-gwern-gpt2-irish-paddywhack.ogg", "/docs/ai/music/2019-10-22-gwern-gpt2-irish-paddywhack.mp3")
  , ("docs/ai/music/2019-10-23-gwern-gpt2-irish-hickeystune.ogg", "/docs/ai/music/2019-10-23-gwern-gpt2-irish-hickeystune.mp3")
  , ("docs/ai/music/2019-12-09-gpt2-combinedabc-100samples.ogg", "/docs/ai/music/2019-12-09-gpt2-combinedabc-100samples.mp3")
  , ("docs/ai/music/2019-10-30-thelonelyfireside.ogg", "/docs/ai/music/2019-10-30-thelonelyfireside.mp3")
  , ("docs/sr/2019-04-22-deepdotweb-dnmlist.hml", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  , ("docs/sr/2019-01-24-deepdotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  , ("Self-decrypting. 2011", "/Self-decrypting")
  , ("\"http://www.emcdda.europa.eu/system/files/publications/12078/20192630_TD0319332ENN_PDF.pdf/\"", "http://www.emcdda.europa.eu/system/files/publications/12078/20192630_TD0319332ENN_PDF.pdf")
  , ("account/profile/05abde47fcf35cd033ff12b9254bf3a0/1", "/tags/Silk%20Road")
  , ("docs/iq/docs/iq/2017-jerrim.pdf", "/docs/iq/2017-jerrim.pdf")
  , ("Drug-Gwern Branwen", "/Drug-heuristics")
  , ("newsletter/2019/index.html", "/tags/newsletter")
  , ("newsletter/2020/index.html", "/tags/newsletter")
  , ("newsletter/2021/index.html", "/tags/newsletter")
  , ("newsletter/2022/index.html", "/tags/newsletter")
  , ("newsletter/2023/index.html", "/tags/newsletter")
  , ("newsletter/2024/index.html", "/tags/newsletter")
  , ("newsletter/2025/index.html", "/tags/newsletter")
  , ("newsletter/2026/index.html", "/tags/newsletter")
  , ("newsletter/2027/index.html", "/tags/newsletter")
  , ("newsletter/2029/index.html", "/tags/newsletter")
  , ("newsletter/2030/index.html", "/tags/newsletter")
  , ("Embryo-selectionhttps://americanpregnancy.org/getting-pregnant/preimplantation-genetic-diagnosis/index.html", "/Embryo-selection")
  , ("gpt-2-preference-learning", "/GPT-2-preference-learning")
  , ("GPT2-preference-learning", "/GPT-2-preference-learning")
  , ("GPT2preferencelearning", "/GPT-2-preference-learning")
  , ("Gpt-2-preference-learning", "/GPT-2-preference-learning")
  , ("GPt-2-preference-learning", "/GPT-2-preference-learning")
  , ("GPT-2-preference-", "/GPT-2-preference-learning")
  , ("GPT-2-preference", "/GPT-2-preference-learning")
  , ("preferencelearning", "/GPT-2-preference-learning")
  , ("preference-learning", "/GPT-2-preference-learning")
  , ("Preference-learning", "/GPT-2-preference-learning")
  , ("docs/spacedrepetition/1939-spitzer.pd", "/docs/spacedrepetition/1939-spitzer.pdf")
  , ("docs/genetics/editing/2019-ceze", "/docs/genetics/editing/2019-ceze.pdf")
  , ("inde", "/index")
  , ("docs/iq/1927-spearman-theabilitiesofman.pdfHorn, J.L. (1991). Measurement of intellectual capabilities: A review of theory. In K.S. McGrew, J.K. Werder, 8r R.W. Woodcock (Eds.), WJ-R technical manuul. Allen, TX: DLM.", "/docs/iq/1927-spearman-theabilitiesofman.pdf")
  , ("GPT2-2", "/GPT-2")
  , ("docs/ai/poetry/2019-12-15-gpt21.5b-poetry-samples", "/docs/ai/poetry/2019-12-15-gpt21.5b-poetry-samples-topp090.txt")
  , ("docs/2019-decabo", "/docs/longevity/2019-decabo.pdf")
  , ("docs/2019-debaco", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf traduzir", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf😊", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdfref", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf&ved=2ahUKEwjL1LPRwtfmAhWOv54KHekTBnIQFjADegQIAhAB&usg=AOvVaw3wetTjnugKCL2sIYPjQeCI&cshid=1577509217868", "/docs/longevity/2019-decabo.pdf")
  , ("docs/2019-decabo.pdf", "/docs/longevity/2019-decabo.pdf")
  , ("docs/2019-decabo.pdf?fbclid=IwAR1SNGP_GmR6mKZqH1XlX8WyqYWk4FW1LHT8KCe_PivefEBSg5baIAzurgE", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longetivity/2019-decabo.net", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longetivity/2019-decabo.pdf", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.PDF", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longetivity/2019-decabo.pdf?fbclid=IwAR3Fds7hcC6Na5ib9_85wAdM2VYVlNwrrSKYGgNuXK5Y6WIt48x261Vt21g", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf](https://www.gwern.net/docs/longevity/2019-decabo.pdf)", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longewity/2019-decabo.pdf", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf」", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.net", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-debaco.pdf", "/docs/longevity/2019-decabo.pdf")
  , ("docs/loquartzngevity/2019-decabo.pdf", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf?fbclid=IwAR0gBkmsGmq8e5Wy4IWtpYTJKTJZniLiZqzmmCocAC2JyZQpQf898RrvArs😉", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf&ved=2ahUKEwj8-8rz1vHmAhXsDbkGHRi-DWsQFjAAegQIARAB&usg=AOvVaw3wetTjnugKCL2sIYPjQeCI&cshid=1578406936233?fbclid=IwAR0EL3gxd7PSqTEb_So80MfxoWVnsDss7PJ-oqVfVyY_ba7XHQigsfvAm_0", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdffiesta se vs s", "/docs/longevity/2019-decabo.pdf")
  , ("2019-decabo.pdf", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019?fbclid=IwAR0AotwhsWwzCxasZ2ylVEMjl_CEI8OtvIpieYMLo2UWhwuczY7ChPkuaMo", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf&ved=2ahUKEwjSyZ7Ytf7mAhVUHM0KHRTLAJYQFjACegQIBBAB&usg=AOvVaw3wetTjnugKCL2sIYPjQeCI&cshid=1578844402723", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf 4 Hide or report this", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf.", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-Delano.pdf", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-cabo.pdf", "/docs/longevity/2019-decabo.pdf")

  , ("docs/spacedrepet…", "/docs/spacedrepetition/index.html")
  , ("docs/psychology/2016-ferguson.pd", "/docs/psychology/2016-ferguson.pdf")
  , ("docs/music-ddissonância cognitivaistraction/2013-brodsky.pdf", "/docs/music-distraction/2013-brodsky.pdf")
  , ("docs/psychology/2016-ferguson.pdf)", "/docs/psychology/2016-ferguson.pdf")
  , ("docs/statistics/decision/1986-bolton", "/docs/statistics/decision/1986-bolton.pdf")
  , ("docs/iq/2008-reeve.pdf)", "/docs/iq/2008-reeve.pdf")
  , ("docs/statistiscs/decision/1994-benter.pdf", "/docs/statistics/decision/1994-benter.pdf")
  , ("docs/philo/1923-ramsey.pdf)", "/docs/philo/1923-ramsey.pdf")
  , ("docs/iq/2018-hegelund.pdf&ved=2ahUKEwjqkqrQxdnmAhXTqHEKHRYtCq4QFjAPegQICRAB&usg=AOvVaw3YvygRbu4DfC1ewvcVM-r2&cshid=1577577373141", "/docs/iq/2018-hegelund.pdf")
  , ("Faces.com", "/Faces")
  , ("signin", "/index")
  , ("Spaced-repetitionhttps://senrigan.io/blog/everything-i-know-strategies-tips-and-tricks-for-spaced-repetition-anki/index.html", "/Spaced-repetition")
  , ("docs/bitcoin/2008-Nakamoto", "/docs/bitcoin/2008-nakamoto")
  , ("docs/longev", "/docs/longevity/index.html")
  , ("docs/nicotine/2019-hajek", "/docs/nicotine/2019-hajek.pdf")
  , ("docs/nicotine/2019-hajek.", "/docs/nicotine/2019-hajek.pdf")
  , ("docs/personal/rss-subscriptions", "/docs/personal/rss-subscriptions.opml")
  , ("docs/statistics/bias/1975-rosenthal-experimenterexpectancyeffects.pdf", "/docs/statistics/bias/1976-rosenthal-experimenterexpectancyeffects.pdf")
  , ("docs/genetics/heritable/1997-rowe.pdf.", "/docs/genetics/heritable/1997-rowe.pdf")
  , ("Danbooru2018）。我将在数据部分讨论它的优缺点，其中一个主要缺点是缺乏多样性：难以生成男性图像。下面所有的例子都是用这个工具生成的。我最初是在", "/Danbooru2019#danbooru2018")
  , ("docs/borges/1952-borges", "/docs/borges/1952-borges-thenightingaleofkeats.pdf")
  , ("docs/iq/2006-dickerson.pdfhttps://www.gwern.net/docs/iq/2006-dickerson.pdf", "/docs/iq/2006-dickerson.pdf")
  , ("Char-RNN", "/RNN-metadata")
  , ("RNN-Metadata", "/RNN-metadata")
  , ("docs/genetic/heritable/2019-bai.pdf", "/docs/genetics/heritable/2019-bai.pdf")
  , ("docs/genetics/heritabe", "/docs/genetics/heritable/index.html")
  , ("docs/spacedrepetition/1916", "/docs/spacedrepetition/1916-murphy.pdf")
  , ("indexnews", "/index")
  , ("Music", "/Music-distraction")
  , ("Danbooru2018", "/Danbooru2019#danbooru2018")
  , ("docs/genetics/selection/19-hecht.pdf?20utm_source=share", "/docs/genetics/selection/2019-hecht.pdf")
  , ("docs/sr/2019-04-22-deepdotweb-dnmlist.htmlsilkroad4n7fwsrw.onion", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  , ("Death-Note-script moo", "/Death-Note-script")
  , ("docs/statistics.decision.1994-benter.pdf", "/docs/statistics/decision/1994-benter.pdf")
  , ("docs/statistics.decision/1994-benter.pdf", "/docs/statistics/decision/1994-benter.pdf")
  , ("market/item/amfetamin-5gram-pasta-dunder-5317e284de", "/tags/Silk%20Road")
  , ("Q29uc2NpZW", "/index")
  , ("The-Melanchol", "/The-Melancholy-of-Subculture-Society")
  , ("tryon", "/Tryon")
  , ("Tryon's", "/Tryon")
  , ("Tryon's-rats", "/Tryon")
  , ("Tryon's-Rats", "/Tryon")
  , ("Tryons-rats", "/Tryon")
  , ("Tryons-Rats", "/Tryon")
  , ("Rats", "/Tryon")
  , ("rats", "/Tryon")
  , ("docs/japanese/2001-debary-sourcesofjapanese", "/docs/japanese/2001-debary-sourcesofjapanesetradition.pdf")
  , (" russia flag", "https://en.wikipedia.org/wiki/Flag_of_Russia")
  , ("Advertising", "Ads")
  , ("docs/genetics/heritable/2008-halder.pdf.", "/docs/genetics/heritable/2008-halder.pdf")
  , ("me", "/Links")
  , ("newsletter/2019/123", "/newsletter/2019/12")
  , ("LSD-microdosing,page", "/LSD-microdosing.page")
  , ("self-decrypting -files", "/Self-decrypting-files")
  , ("docs/psychology/writing/1970-vernon-creativity.pdf overachievement", "/docs/psychology/writing/1970-vernon-creativity.pdf")
  , ("docs/spacedrepetition/2001-maquet.pdf.", "/docs/spacedrepetition/2001-maquet.pdf")
  , ("Replications", "/Replication")
  , ("docs/sociology/1999-lee.pdf]", "/docs/sociology/1999-lee.pdf")
  , ("Coin-flip.html", "/Coin-flip")
  , ("docs/genetics/heritable/2019-bai.pdf https://jamanetwork.com/journals/jamapsychiatry/article-abstract/2737582", "/docs/genetics/heritable/2019-bai.pdf")
  , ("docs/genetics/heritable/2019-bai.pdf%20https://jamanetwork.com/journals/jamapsychiatry/article-abstract/2737582", "/docs/genetics/heritable/2019-bai.pdf")
  , ("Melatoniin", "/Melatonin")
  , ("docs/sr/201dream9-04-22-deepdotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  , ("docs/sr/2019-04-deepdotweb-dnist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  , ("docs/sr/2019-04-deepdotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  , ("docs/sr/2019-04-22-deepcivet cat for saledotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  , ("docs/sr/2019-04-22-deepdotweb-dnfmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  , ("docs/sr/2019-04-22-deepdotweb-dnmlistJUSQU A QUELLE HEURE LE COURRIER EST MIVR2html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  , ("docs/sr/2019-03-22-deepdotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  , ("docs/sr/2019-03-22-deepdotyweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  , ("docs/sr/2019-04-22-http://tt2mopgckifmberr.onion-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  , ("docs/rotten.com/library/bio/presidents/ ronald-reagan/index.html", "/docs/rotten.com/library/bio/presidents/ronald-reagan/index.html")
  , ("docs/rotten.com/library/bio/presidents/ronald-reagan/index.html.", "/docs/rotten.com/library/bio/presidents/ronald-reagan/index.html")
  , ("DNM-archives.", "/DNM-archives")
  , ("doc[...]ndattraction20092014.html", "/docs/psychology/okcupid/raceandattraction20092014.html")
  , ("doc/melatonin/2014-boergers.pdf", "/docs/melatonin/2014-boergers.pdf")
  , ("docs/psychology/2019-letexier.pdf.", "/docs/psychology/2019-letexier.pdf")
  , ("does/psychology/2019-letexier.pdf", "/docs/psychology/2019-letexier.pdf")
  , ("statiic/imgg/icons/newyorktimes.svg", "/static/img/icons/newyorktimes.svg")
  , ("static/imgg/icons/newyorktimes.svg", "/static/img/icons/newyorktimes.svg")
  , ("Borges", "/docs/borges/index.html")
  , ("Danbooru2020", "/Danbooru2019")
  , ("danbooru2020", "/Danbooru2019")
  , ("Danbooru2021", "/Danbooru2019")
  , ("danbooru2021", "/Danbooru2019")
  , ("docs/rotten.com/library/religion/Mormonism/index.html", "/docs/rotten.com/library/religion/mormonism/index.html")
  , ("reinforcement/index.html", "/docs/rl/index.html")
  , ("docs/math/1926-ramsey.pdf.com", "/docs/math/1926-ramsey.pdf")
  , ("DnM-arrests", "/DNM-arrests")
  , ("traffic", "/Traffic")
  , ("docs/psychology/3019-lim.pdf", "/docs/psychology/2019-lim.pdf")
  , ("docs/borgesdf", "/docs/borges/index.html")
  , ("Book-reviewsInboxx", "/Book-reviews")
  , ("docs/culture/1935-eliot.pdf.", "/docs/culture/1935-eliot.pdf")
  , ("docs/sociology/2018-chaiyachati.pdf22.Marcus AC, Crane LA, Kaplan CP, et al. Improving adherence to screening follow-up among women with abnormal pap smears: Results from a large clinic- based trial of three intervention strategies. Med Care. 1992", "/docs/sociology/2018-chaiyachati.pdf")
  , ("iodinne", "/Iodine")
  , ("F", "/Faces")
  , ("Bacopa.html", "Nootropics#bacopa")
  , ("docs/statistics/bias/2019-kvarven", "/docs/statistics/bias/2019-kvarven.pdf")
  , ("docs/statistics/bias/2019-kvarven.odf", "/docs/statistics/bias/2019-kvarven.pdf")
  , ("docs/rotten.com/library/history/huac/index.htm", "/docs/rotten.com/library/history/huac/index.html")
  , ("docs/statistics/bayes/1814-laplace-philosophicalessayonprobabilities-ch1probabilitiestestimonies.pdf", "/docs/statistics/bayes/1814-laplace-philosophicalessayonprobabilities-ch5probabilitiestestimonies.pdf")
  , ("docs/statistics/bayes/1814-laplace-philosophicalessayonprobabilities", "/docs/statistics/bayes/1814-laplace-philosophicalessayonprobabilities-ch5probabilitiestestimonies.pdf")
  , ("docs/ai/2019-toppol.pdf", "/docs/ai/2019-topol.pdf")
  , ("docs/ai/1986-michie-onmachine intell", "/docs/ai/1986-michie-onmachineintelligence.pdf")
  , ("docs/ai/1986-michie-onmachoneintelligence.pdf", "/docs/ai/1986-michie-onmachineintelligence.pdf")
  , ("docs/historyfischer M. Well-ordered liscense/1986-dietz.pdf", "/docs/history/1986-dietz.pdf")
  , ("docs/psychology/okcupid/itseemsthatwomenlieabouttheirheightmorethanmendo.html_", "/docs/psychology/okcupid/itseemsthatwomenlieabouttheirheightmorethanmendo.html")
  , ("docs/psychology/okcupid/raceandattraction20092014.html_", "/docs/psychology/okcupid/raceandattraction20092014.html")
  , ("docs/ai/poetry/index.html", "https://www.google.com/search?q=site:www.gwern.net/docs/ai/poetry/&num=100&filter=0")
  , ("Benter", "/docs/statistics/decision/1994-benter.pdf")
  , ("benter", "/docs/statistics/decision/1994-benter.pdf")
  , ("Searchreply", "/Search")
  , ("docs/sociology/1981-gubaeffectiveevaluation.pdf", "/docs/sociology/1981-guba-effectiveevaluation.pdf")
  , ("docs/genetics/heritable/2019-xing.pdf.", "/docs/genetics/heritable/2019-xing.pdf")
  , ("docs/music-distraction-2019-gonzales.pdf", "/docs/music-distraction.2019-gonzales.pdf")
  , ("Searc?fbclid=IwAR1J9DvAR7wMeL3rH0gVsx__JH6e4wOLepJAupoFVoILeqo8zXUD1y47tCk", "/Search")
  , ("Searc", "/Search")
  , ("Subscript", "/Subscripts")
  , ("subscript", "/Subscripts")
  , ("subscripts", "/Subscripts")
  , ("Subscripting", "/Subscripts")
  , ("subscripting", "/Subscripts")
  , ("docs/ai/2019-12-16-gpt21.5b-poetry-samples-topp080.txt", "/docs/ai/poetry/2019-12-16-gpt21.5b-poetry-samples-topp080.txt")
  , ("docs/catnip/2017-vanhaaften.pdfterminal santa luzia uberlandia xerox endereço", "/docs/catnip/2017-vanhaaften.pdf")
  , ("docs/co2/2015-stafford.pdf] in", "/docs/co2/2015-stafford.pdf")
  , ("docs/music-distraction/2014.perham.pdf", "/docs/music-distraction/2014-perham.pdf")
  , ("wp-login.php%3Faction%3Dregister", "/index")
  , ("docs/ai/2019-07-22-gpt2-345m-taotehching-all-ch181.tar.xz", "/docs/ai/poetry/2019-07-22-gpt2-345m-taotehching-all-ch181.tar.xz")
  , ("docs/bitcoin/2008-nakamotovox", "/docs/bitcoin/2008-nakamoto")
  , ("docs/psychology/okcupid/howyourraceaffectsthemessagesyouget.html_", "/docs/psychology/okcupid/howyourraceaffectsthemessagesyouget.html")
  , ("Spaced-repetition__", "/Spaced-repetition")
  , ("Docs/Statistics/Bayes/1995-Cavin.pdf.", "/docs/statistics/bayes/1995-cavin.pdf")
  , ("docs/rotten.com/library/religion/Marian_Apparitions/index.html", "/docs/rotten.com/library/religion/marian-apparitions/index.html")
  , ("docs/catnip/2017-espiniturbe.pdf.", "/docs/catnip/2017-espiniturbe.pdf")
  , ("docs/longevity/2019-decabo.pd", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf?fbclid=IwAR0fgZ07Ju5O9IKpUyfTgRFK67S1Mnqnx6r84-uX6N64THchjS1yedHJfMw", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf?fbclid=IwAR3AqzoT0a70L9s5T7Ii-MWCDMYFJ0WWPH8WxDAW_zuSB8l7j13MspFxtRw", "/docs/longevity/2019-decabo.pdf")
  , ("docs/sr/2018-tzanetakis.pdf http://linkinghub.elsevier.com/retrieve/pii/UzA5NTUzOT", "/docs/sr/2018-tzanetakis.pdf")
  , ("U3BhY2VkJT", "/index")
  , ("docs/psychology/2019-lim.pdftetracoricas y policoricas", "docs/psychology/2019-lim.pdf")
  , ("static/robots.txt", "/robots.txt")
  , ("docs/psychology/okcupid/shortermenaremorelikelytobegay.Dunno", "/docs/psychology/okcupid/shortermenaremorelikelytobegay.html")
  , ("Banbooru2019", "/Danbooru2019")
  , ("Danbooru2018), crop the faces using [lbpcascade_animeface](https://github.com/nagadomi/lbpcascade_animeface", "/Danbooru2018")
  , ("docs/rotten.com/library/sex/watersports/index.htmlhorror porn pissing woman", "/docs/rotten.com/library/sex/watersports/index.html")
  , ("Search.age", "/Search.page")
  , ("docs/biology/aboutidx.html" , "/docs/biology/index.html")
  , ("newsletter/2019/docs/www/danluu.com/2f03db95954c6aae4c9e2273ffac2ee574a113cb.html", "https://danluu.com/term-latency/")
  , ("docs/genetics/editing/2019-anzalone.pdf&ved=2ahUKEwiOqJqbi9vnAhWtJzQIHYTgCjsQFjAQegQICBAB&usg=AOvVaw3ynnQMoiRhqDcwf9lVa23X&cshid=1582028506912", "/docs/genetics/editing/2019-anzalone.pdf")
  , ("docs/genetics/editing/2019-anzalone.pdf&ved=2ahUKEwiOqJqbi9vnAhWtJzQIHYTgCjsQFjAQegQICBAB&usg=AOvVaw3ynnQMoiRhqDcwf9lVa23X&cshid=1582028582189", "/docs/genetics/editing/2019-anzalone.pdf")
  , ("docs/music-distraction/1989-salame.pdf citation", "/docs/music-distraction/1989-salame.pdf")
  , ("newsletter/2019/docs/www/old.reddit.com/4af39bdcabcf613916ab4b8077dc0f09e83c2b58.html", "/docs/www/old.reddit.com/4af39bdcabcf613916ab4b8077dc0f09e83c2b58.html")
  , ("assets/20171109/biped/learning_to_fall.gif", "http://blog.otoro.net/assets/20171109/biped/learning_to_fall.gif")
  , ("blog/chasing-10x-leveraging-a-poor-memory-in-software-engineering/index.html", "https://senrigan.io/blog/chasing-10x-leveraging-a-poor-memory-in-software-engineering/")
  , ("nicotene", "/Nicotine")
  , ("poetry", "/GPT-2-poetry")
  , ("links.page", "/Links")
  , ("newsletter/2020/1", "/newsletter/2020/01")
  , ("tracker?aat=1", "/index")
  , ("images/iq/oliviera-2012-hydrocephaly-retracted-mislabeledimage.jpg", "/images/iq/oliveira-2012-hydrocephaly-retracted-mislabeledimage.jpg")
  , ("docs/www/reddit.com/2ba72007b23422f532f93511f38a2ba1c5afe3c7.html", "https://www.reddit.com/r/SubSimulatorGPT2Meta/comments/ccvspt/update_experimenting_with_generating_hybrid/")
  , ("SearchResults.jsp?q=securities+regulation", "/index")
  , ("DNM-archives&lt", "/DNM-archives")
  , ("docs/www/fivethirtyeight.com/bc564ad2036c7dee26bf7c670ea3bc95116bea8d.htmlscheme=https&postMessageOrigin=https://www.gwern.net/docs/www/fivethirtyeight.com/bc564ad2036c7dee26bf7c670ea3bc95116bea8d.html&config=PROD&logLevel=INFO&topHost=www.gwern.net&cssOverride=https://fivethirtyeight.com/wp-content/themes/espn-fivethirtyeight/assets/css/oneid.min.css&responderPage=https://fivethirtyeight.com/oneid-responder&buildId=16ff932d35f", "/docs/www/fivethirtyeight.com/bc564ad2036c7dee26bf7c670ea3bc95116bea8d.html")
  , ("docs/www/neomarxisme.com/.http://neomarxisme.com/wdmwordpress/index.html?p=88", "http://neomarxisme.com/wdmwordpress/?p=88")
  , ("flexible", "/About#design")
  , ("docs/longevity/2019-decabo.pdf%E2%80%AC", "/docs/longevity/2019-decabo.pdf")
  , ("docs/longevity/2019-decabo.pdf%E2%80%AC?fbclid=IwAR0fgZ07Ju5O9IKpUyfTgRFK67S1Mnqnx6r84-uX6N64THchjS1yedHJfMw", "/docs/longevity/2019-decabo.pdf")
  , ("docs/https://www.gwern.net/docs/longevity/2019-decabo.pdf", "/docs/longevity/2019-decabo.pdf")
  , ("dic/longevity/3019decabo", "/docs/longevity/2019-decabo.pdf")
  , ("doc/longvity/2019-decabo.pdf", "/docs/longevity/2019-decabo.pdf")
  , ("Black-market survival.", "/DNM-survival")
  , ("docs/rotten.com/library/bio/crime/serial-killers/david-edward-maust/index.html.", "/docs/rotten.com/library/bio/crime/serial-killers/david-edward-maust/index.html")
  , ("Linksep", "/Links")
  , ("docs/is/2007-sterne.pdf", "/docs/iq/2007-sterne.pdf")
  , ("docs/www/bentilly.blogspot.com/bf5845a44010c266a9658ab9f915a6b62ccf97dc.htmlnyt", "/docs/www/bentilly.blogspot.com/bf5845a44010c266a9658ab9f915a6b62ccf97dc.html")
  , ("docs/iq/1941-thurstone-factorialstudiesofintelligence.pdf&ved=2ahUKEwi236KZzPHnAhXslIsKHVkcAkwQFjAAegQIAhAB&usg=AOvVaw2qlAabmcbbT0ujhWvAooNL", "/docs/iq/1941-thurstone-factorialstudiesofintelligence.pdf")
  , ("docs/iq/1972-matarazzo.PDF", "/docs/iq/1972-matarazzo.pdf")
  , ("psychology/1969-torrance.pdf", "/docs/psychology/1969-torrance.pdf")
  , ("2018/12", "/newsletter/2018/12")
  , ("docs/genetics/correlation/22019-ross.pdf", "/docs/genetics/correlation/2019-ross.pdf")
  , ("print?id=1657", "/index")
  , ("rotten", "/docs/rotten.com/library/index.html")
  , ("docs/rotten.com/index.html", "/docs/rotten.com/library/index.html")
  , ("twnde", "/TWDNE")
  , ("docs/rotten.com/library/conspiracy/pnac/in", "/docs/rotten.com/library/conspiracy/pnac/index.html")
  , ("docs/psychology/okcupid/weexperimentonhumanbein",  "/docs/psychology/okcupid/weexperimentonhumanbeings.html")
  , ("Improvementscatloging", "/Improvements")
  , ("Improvementst", "/Improvements")
  , ("Modafinil]", "/Modafinil")
  , ("newsletter/13", "/tags/newsletter")
  , ("images/1737-bayle-dictionary-vol4-pg901.jpg", "/images/design/1737-bayle-dictionary-vol4-pg901.jpg")
  , ("djhshih/argparser/src/master/index.html", "https://bitbucket.org/djhshih/argparser/src/master/")
  , ("improvenets", "/Improvements")
  , ("improvents", "/Improvements")
  , ("improvent", "/Improvements")
  , ("lllyasviel/style2paints", "https://github.com/lllyasviel/style2paints")
  , ("refs", "/index")
  , ("docs/statistics/causality/2019-schellenberg.dock", "/docs/statistics/causality/2019-schellenberg.pdf")
  , ("docs/math/1990-thomason.pdf)", "/docs/math/1990-thomason.pdf")
  , ("SearchResults.jsp?q=C", "/Search")
  , ("docs.iq/2014-warne.pdf", "/docs/iq/2014-warne.pdf")
  , ("Fdocs/statistics/decision/1994-benter.pdf", "/docs/statistics/decision/1994-benter.pdf")
  , (" Faces", "/Faces")
  , ("anime-faces-character-faces", "/Faces#anime-faces-character-faces")
  , ("docs/music-distraction/2011-huang.pf", "/docs/music-distraction/2011-huang.pdf")
  , ("docs/math/1893-heaviside.pdf", "/docs/math/1892-heaviside.pdf")
  , ("docs/math/1894-heaviside.pdf", "/docs/math/1892-heaviside.pdf")
  , ("docs/iq/1966-shuey-thetestingofnegrointelligencevol2.pdf", "/docs/iq/1982-osborne-thetestingofnegrointelligencevol2.pdf")
  , ("Improvements)", "/Improvements")
  , ("Faces<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.gwern.net_Faces&d=DwMFaQ&c=zwPfxOisiRWGoGc9Pq9Wrg&r=Vuy6f--MIX_gzOBL1_VqW58GN_cdVbrY0fLGqljxDGw&m=jelmvHiyhFyCsqmZAcwDorgw6Y5-E0qr45RrS5cafhg&s=a-cRB5NsQcZke8wHKTkrttmivGqRDERk75e4bU5zrrA&e=", "/Faces")
  , ("docs/sr/pickard/2003-pickard-lsd-trial-transcript-gordontoddskinner-05-1.pdf", "/docs/sr/pickard/2003-pickard-lsd-trial-transcript-gordontoddskinner-05.pdf")
  , ("elephant", "https://www.thenewatlantis.com/publications/do-elephants-have-souls")
  , ("docs/it/1963-rosenthal.pdu", "/docs/iq/1963-rosenthal.pdf")
  , ("STATIC/JS/POPUPS.JS", "/static/js/popups.js")
  , ("docs/cs/1955-nash)", "/docs/cs/1955-nash")
  , ("docs/economics/2018-creditsuisse.pdf", "/docs/economics/2013-creditsuisse.pdf")
  , ("docs/longevity/2019-decabo.pdf‬?fbclid=IwAR0jxCyTPmI_sk41ue_IjeHqbpLiYLCkUTwrWFolIzoOEU044BDj3PXdByo", "/docs/longevity/2019-decabo.pdf")
  , ("indes", "/index")
  , ("space-repetition", "/Spaced-repetition")
  , ("Melatonin.", "/Melatonin")
  , ("docs /borges/1977-borges-blindness.pdf", "/docs/borges/1977-borges-blindness.pdf")
  , ("docs/iq/2014-hyde.pdfmerger,", "/docs/iq/2014-hyde.pdf")
  , ("docs/nicotine/2003-shiffman.pdf'I", "/docs/nicotine/2003-shiffman.pdf")
  , ("ttft/print/TTFT.pdf", "https://numinous.productions/ttft/print/TTFT.pdf")
  , ("Improvements。", "/Improvements")
  , ("docs/SR/2019-04-22-deepdotweb-dnmlist.html", "/docs/sr/2019-04-22-deepdotweb-dnmlist.html")
  ]
